// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

public partial class API
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA { get; set; } = null!;

    [StringLength(150)]
    public string TEN { get; set; } = null!;

    [StringLength(300)]
    public string URL { get; set; } = null!;

    public int? THU_TU { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }
}