// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class API
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA { get; set; }

    [Required]
    [StringLength(150)]
    public string TEN { get; set; }

    [Required]
    [StringLength(300)]
    public string URL { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }
}