// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

public partial class API_TOKENS
{
    [Key]
    public long ID { get; set; }

    public long ID_TAI_KHOAN_GUI_TIN { get; set; }

    [StringLength(50)]
    public string TAI_KHOAN { get; set; } = null!;

    [StringLength(250)]
    public string MAT_KHAU { get; set; } = null!;

    [StringLength(20)]
    public string IP_ADDRESS { get; set; } = null!;

    [StringLength(500)]
    public string AUTH_TOKEN { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime EXPIRES_ON { get; set; }
}