// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_PHIEU", "MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "THANG", "NAM", "MA_DM_KHOAN_THU_SO", "MA_KHOI", "MA_NHOM_TUOI_MN", "MA_HOC_SINH", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", "THANG", "NAM", Name = "IX_NAM_SO_CAP_TRUONG_THANG_NAM")]
[Index("MA_NAM_HOC", "MA_SO_GD", "THANG", "NAM", Name = "IX_NAM_SO_THANG_NAM")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class BCS_HOC_SINH_KHOAN_THU_THANG
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_PHIEU { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_CAP_HOC { get; set; }

    public int MA_NAM_HOC { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_DM_KHOAN_THU_SO { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_KHOI { get; set; }

    [StringLength(50)]
    public string MA_NHOM_TUOI_MN { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_LOP { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }

    [Required]
    [StringLength(250)]
    public string TEN_HOC_SINH { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? SO_TIEN { get; set; }

    public int TRANG_THAI { get; set; }

    public int IS_DONG_BO { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}