// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "THANG", "NAM", "MA_DM_KHOAN_THU_SO", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", "THANG", "NAM", Name = "IX_NAM_SO_CAP_TRUONG_THANG_NAM")]
[Index("MA_NAM_HOC", "MA_SO_GD", "THANG", "NAM", Name = "IX_NAM_SO_THANG_NAM")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class BCS_HOC_SINH_DK_KHOAN_THU
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    [StringLength(50)]
    public string MA_DM_KHOAN_THU_SO { get; set; } = null!;

    public int? TONG_SO_HS { get; set; }

    public int? DDK_SL { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? DDL_TL { get; set; }

    public int? CDK_SL { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CDL_TL { get; set; }

    public int TRANG_THAI { get; set; }

    public int IS_DONG_BO { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}