// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class CAP_MA_HOC_SINH
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    public long THU_TU { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }
}