// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class CAP_MA_PHIEU_THU
{
    [Key]
    public long ID { get; set; }

    public int MA_NAM_HOC { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_PHIEU_THU { get; set; }

    [Required]
    [StringLength(50)]
    public string TIEN_TO_PHIEU_THU { get; set; }

    public long? STT_PHIEU_THU { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    public long? ID_DOT_THU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }

    public long? STT_PHIEU_THU_TRUONG { get; set; }
}