// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("ID_LSTT", "ID_HOC_SINH", Name = "IX_KEY", IsUnique = true)]
[Index("MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", "NAM_TC", Name = "IX_MA_SO_GD_MA_CAP_HOC_MA_TRUONG_NAM_TC_ET")]
[Index("NAM_TC", "MA_SO_GD", "MA_CAP_HOC", "ID_TRUONG", Name = "IX_NAMTC_SO_CAP_ID_TRUONG")]
[Index("NAM_TC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAMTC_SO_CAP_MA_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "ID_TRUONG", Name = "IX_NAM_SO_CAP_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", "ID_LSTT", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_LSTT_ID_HOC_SINH")]
[Index("STT_BIEN_LAI", Name = "IX_STT_BIEN_LAI")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "NAM_HOC_SO_GD_CAP_HOC_TRUONG_STT_BIEN_LAI")]
public partial class CAP_MA_BIEN_LAI
{
    [Key]
    public long ID { get; set; }

    public int MA_NAM_HOC { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    public long ID_LSTT { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    [StringLength(50)]
    public string SO_BIEN_LAI { get; set; } = null!;

    public long STT_BIEN_LAI { get; set; }

    public int? NAM_TC { get; set; }
}