// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("TEN_MIEN", Name = "IX_KEY", IsUnique = true)]
public partial class CAU_HINH_TEN_MIEN
{
    [Key]
    public long ID { get; set; }

    [StringLength(250)]
    public string TEN_MIEN { get; set; }

    [StringLength(50)]
    public string MA_CAP_DON_VI { get; set; }

    [StringLength(50)]
    public string MA_DON_VI { get; set; }

    [StringLength(250)]
    public string LOGO { get; set; }

    [StringLength(250)]
    public string TEN_DON_VI { get; set; }

    [StringLength(250)]
    public string TEN_PHAN_MEM { get; set; }

    [StringLength(250)]
    public string ANH_DANG_NHAP_1 { get; set; }

    [StringLength(250)]
    public string ANH_DANG_NHAP_2 { get; set; }

    [StringLength(250)]
    public string ANH_DANG_NHAP_3 { get; set; }

    [StringLength(250)]
    public string HOT_LINE { get; set; }

    [StringLength(250)]
    public string EMAIL { get; set; }

    [StringLength(250)]
    public string ICON { get; set; }
}