// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("ID_TRUONG", Name = "IDX_CAU_HINH_TRUONG_ID_TRUONG")]
[Index("MA_CAP_HOC", Name = "IDX_CAU_HINH_TRUONG_MA_CAP_hOC")]
[Index("MA_NAM_HOC", Name = "IDX_CAU_HINH_TRUONG_MA_NAM_HOC")]
[Index("MA_NAM_HOC", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_CAU_HINH_TRUONG_UNIQUE", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
public partial class CAU_HINH_TRUONG
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string MA_PHONG_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_TRUONG { get; set; }

    public int MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string MA_CAP_HOC { get; set; }

    public int? IS_KHOA_K1 { get; set; }

    public int? IS_KHOA_K2 { get; set; }

    public int THANG_DAU_KY_I { get; set; }

    public int THANG_CUOI_KY_I { get; set; }

    public int THANG_DAU_KY_II { get; set; }

    public int THANG_CUOI_KY_II { get; set; }

    public int NGAY_DAU_KY_I { get; set; }

    public int NGAY_CUOI_KY_I { get; set; }

    public int NGAY_DAU_KY_II { get; set; }

    public int NGAY_CUOI_KY_II { get; set; }

    public int NAM_DAU_KY_I { get; set; }

    public int NAM_CUOI_KY_I { get; set; }

    public int NAM_DAU_KY_II { get; set; }

    public int NAM_CUOI_KY_II { get; set; }

    /// <summary>
    /// Không hiện học sinh nghỉ học, chuyển trường, kỷ luật, miễn môn...(mặc định là hiện):
    /// 0: Có hiện
    /// 1: Không hiện
    /// </summary>
    public int IS_KHONG_HIEN_HOC_SINH_KHONG_HOC { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }
}