// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_KHOI", "ID_HOC_SINH", "MA_HOC_SINH", "ID_KHOAN_THU", "THANG", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class DIEM_DANH_KHOAN_THU
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    public long ID_KHOAN_THU { get; set; }

    public int THANG { get; set; }

    public int NGAY_1 { get; set; }

    public int NGAY_2 { get; set; }

    public int NGAY_3 { get; set; }

    public int NGAY_4 { get; set; }

    public int NGAY_5 { get; set; }

    public int NGAY_6 { get; set; }

    public int NGAY_7 { get; set; }

    public int NGAY_8 { get; set; }

    public int NGAY_9 { get; set; }

    public int NGAY_10 { get; set; }

    public int NGAY_11 { get; set; }

    public int NGAY_12 { get; set; }

    public int NGAY_13 { get; set; }

    public int NGAY_14 { get; set; }

    public int NGAY_15 { get; set; }

    public int NGAY_16 { get; set; }

    public int NGAY_17 { get; set; }

    public int NGAY_18 { get; set; }

    public int NGAY_19 { get; set; }

    public int NGAY_20 { get; set; }

    public int NGAY_21 { get; set; }

    public int NGAY_22 { get; set; }

    public int NGAY_23 { get; set; }

    public int NGAY_24 { get; set; }

    public int NGAY_25 { get; set; }

    public int NGAY_26 { get; set; }

    public int NGAY_27 { get; set; }

    public int NGAY_28 { get; set; }

    public int NGAY_29 { get; set; }

    public int NGAY_30 { get; set; }

    public int NGAY_31 { get; set; }

    public int TONG_THANG { get; set; }

    public int TONG_THANG_TAM { get; set; }

    public int SO_NGAY_DA_THU_TIEN { get; set; }

    public int SO_NGAY_THUA { get; set; }

    public int DA_CHOT { get; set; }

    [StringLength(250)]
    public string? GHI_CHU { get; set; }

    public int IS_AUTO { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [ForeignKey("ID_HOC_SINH")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual HOC_SINH ID_HOC_SINHNavigation { get; set; } = null!;

    [ForeignKey("ID_KHOAN_THU")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual KHOAN_THU ID_KHOAN_THUNavigation { get; set; } = null!;

    [ForeignKey("ID_LOP")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual LOP ID_LOPNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; } = null!;

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("DIEM_DANH_KHOAN_THU")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;
}