// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class DM_CAP_DON_VI
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; }

    [Required]
    [StringLength(50)]
    public string TEN { get; set; }

    public int? THU_TU { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_SOURCE { get; set; }

    [InverseProperty("MA_CAP_DON_VINavigation")]
    public virtual ICollection<PHONG_BAN> PHONG_BAN { get; set; } = new List<PHONG_BAN>();
}