// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class DM_DIEN_CHINH_thuphiCH
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; }

    [Required]
    [StringLength(100)]
    public string TEN { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public int? IS_MN { get; set; }

    public int? IS_C1 { get; set; }

    public int? IS_C2 { get; set; }

    public int? IS_C3 { get; set; }

    public int? IS_GDTX { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_SOURCE { get; set; }
}