// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA", Name = "IX_KEY_DM_HINH_THUC_THANH_TOANUNIQUE", IsUnique = true)]
public partial class DM_HINH_THUC_THANH_TOAN
{
    [Key]
    public long ID { get; set; }

    public int MA { get; set; }

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [StringLength(250)]
    public string? GHI_CHU { get; set; }

    public int? THU_TU { get; set; }

    public int? TRANG_THAI { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}