// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_GD", "MA_NAM_HOC", "MA_DM_NHOM_SO", "MA_DM_KHOAN_THU_SO", Name = "IX_KEY", IsUnique = true)]
public partial class DM_KHOAN_THU_SO_NHOM_DV
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    public int MA_NAM_HOC { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_DM_NHOM_SO { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_DM_KHOAN_THU_SO { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CAP_MN { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CAP_TH { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CAP_THCS { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CAP_THPT { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CAP_GDTX { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}