// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_CAP_HOC", "MA_NAM_HOC", "MA", Name = "IX_KEY", IsUnique = true)]
public partial class DM_KHOAN_THU
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(50)]
    public string? MA { get; set; }

    [StringLength(200)]
    public string TEN { get; set; } = null!;

    public int DON_VI_TINH { get; set; }

    public int KY_THU { get; set; }

    public int? THOI_DIEM_THU_Q1 { get; set; }

    public int? THOI_DIEM_THU_Q2 { get; set; }

    public int? THOI_DIEM_THU_Q3 { get; set; }

    public int? THOI_DIEM_THU_Q4 { get; set; }

    public int? THOI_DIEM_THU_K1 { get; set; }

    public int? THOI_DIEM_THU_K2 { get; set; }

    public int? THOI_DIEM_THU_CN { get; set; }

    public int IS_BAT_BUOC { get; set; }

    public int IS_MIEN_GIAM { get; set; }

    public int IS_XUAT_HD { get; set; }

    public int IS_XUAT_CT { get; set; }

    public int IS_THU_NOI_BO { get; set; }

    public int IS_DIEM_DANH { get; set; }

    public int IS_KHAU_TRU { get; set; }

    public int? NAM_BAT_DAU { get; set; }

    public int TRANG_THAI { get; set; }

    public int? THU_TU { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}