// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_CAP_HOC", Name = "IX_CAP_HOC")]
[Index("MA", "MA_CAP_HOC", Name = "IX_CAP_HOC_MA", IsUnique = true)]
[Index("MA", Name = "IX_DM_KHOI", IsUnique = true)]
public partial class DM_KHOI
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string MA { get; set; } = null!;

    [StringLength(50)]
    public string? MA_CAP_HOC { get; set; }

    [StringLength(50)]
    public string? TEN { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(20)]
    public string? MA_LOAI_LOP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("DM_KHOI")]
    public virtual DM_CAP_HOC? MA_CAP_HOCNavigation { get; set; }
}