// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA", "MA_NAM_HOC", Name = "IX_KEY", IsUnique = true)]
public partial class DM_MIEN_GIAM
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(50)]
    public string MA { get; set; } = null!;

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [StringLength(250)]
    public string? GHI_CHU { get; set; }

    public int? THU_TU { get; set; }

    public int? TRANG_THAI { get; set; }

    public int IS_CAP_MN { get; set; }

    public int IS_CAP_TH { get; set; }

    public int IS_CAP_THCS { get; set; }

    public int IS_CAP_THPT { get; set; }

    public int IS_CAP_GDTX { get; set; }

    public long? ID_DM_MIEN_GIAM_SO { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(50)]
    public string? MA_DM_MIEN_GIAM_SO { get; set; }

    [InverseProperty("ID_DM_MIEN_GIAMNavigation")]
    public virtual ICollection<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; } = new List<HOC_SINH_MIEN_GIAM>();

    [InverseProperty("ID_DM_MIEN_GIAMNavigation")]
    public virtual ICollection<KHOAN_THU_MIEN_GIAM> KHOAN_THU_MIEN_GIAM { get; set; } = new List<KHOAN_THU_MIEN_GIAM>();

    [InverseProperty("ID_DM_MIEN_GIAMNavigation")]
    public virtual ICollection<MAP_MIEN_GIAM_HS> MAP_MIEN_GIAM_HS { get; set; } = new List<MAP_MIEN_GIAM_HS>();

    [InverseProperty("ID_DM_MIEN_GIAMNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}