// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

public partial class DM_NHOM_CAN_BO
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; } = null!;

    [StringLength(50)]
    public string TEN { get; set; } = null!;

    public int? THU_TU { get; set; }

    public int? IS_MN { get; set; }

    public int? IS_C1 { get; set; }

    public int? IS_C2 { get; set; }

    public int? IS_C3 { get; set; }

    public int? IS_GDTX { get; set; }

    public int? IS_PHONG { get; set; }

    public int? IS_SO { get; set; }

    public int? IS_BO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}