// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class DM_TINH
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; } = null!;

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(50)]
    public string? CAP { get; set; }

    [StringLength(20)]
    public string MA_SOURCE { get; set; } = null!;

    [InverseProperty("MA_TINHNavigation")]
    public virtual ICollection<DM_HUYEN> DM_HUYEN { get; set; } = new List<DM_HUYEN>();

    [InverseProperty("MA_TINHNavigation")]
    public virtual ICollection<DM_XA> DM_XA { get; set; } = new List<DM_XA>();
}