// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class DM_TRANG_THAI_HOC_SINH
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; }

    [StringLength(20)]
    public string MA_CHUYEN_DEN_CHUYEN_DI { get; set; }

    [Required]
    [StringLength(50)]
    public string TEN { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_SOURCE { get; set; }
}