// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA", Name = "IX_DM_XA")]
[Index("MA_TINH", Name = "IX_DM_XA_2")]
[Index("MA_HUYEN", Name = "IX_DM_XA_3")]
[Index("MA", "MA_NAM_HOC", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", Name = "IX_NAM_HOC")]
[Index("MA_NAM_HOC", "MA_TINH", Name = "IX_NAM_HOC_TINH")]
[Index("MA_NAM_HOC", "MA_TINH", "ID_HUYEN", Name = "IX_NAM_HOC_TINH_HUYEN")]
public partial class DM_XA
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string MA { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string MA_TINH { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HUYEN { get; set; }

    [StringLength(20)]
    public string MA_HUYEN { get; set; } = null!;

    [StringLength(50)]
    public string TEN { get; set; } = null!;

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(20)]
    public string? CAP { get; set; }

    [StringLength(20)]
    public string? MA_XA_SAP_NHAP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    [ForeignKey("ID_HUYEN")]
    [InverseProperty("DM_XA")]
    public virtual DM_HUYEN? ID_HUYENNavigation { get; set; }

    [ForeignKey("MA_TINH")]
    [InverseProperty("DM_XA")]
    public virtual DM_TINH MA_TINHNavigation { get; set; } = null!;
}