// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_DOI_TAC_THANH_TOAN_UNIQUE", IsUnique = true)]
public partial class DOI_TAC_THANH_TOAN
{
    [Key]
    public long ID { get; set; }

    public int MA { get; set; }

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [StringLength(250)]
    public string? GHI_CHU { get; set; }

    public int? THU_TU { get; set; }

    public int? TRANG_THAI { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [InverseProperty("ID_DOI_TAC_THANH_TOANNavigation")]
    public virtual ICollection<TRUONG_DOI_TAC_THANH_TOAN> TRUONG_DOI_TAC_THANH_TOAN { get; set; } = new List<TRUONG_DOI_TAC_THANH_TOAN>();
}