// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_SO_TRUONG_CAP_NAM")]
public partial class DOT_THU_TU_NGUYEN
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [StringLength(500)]
    public string? MO_TA { get; set; }

    [StringLength(500)]
    public string? URL_VAN_BAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_GIAN_BAT_DAU { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_GIAN_KET_THUC { get; set; }

    [StringLength(500)]
    public string? DOI_TUONG_TEXT { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}