// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "HOC_KY", "THANG", "NAM", "ID_DOT_THU", "ID_KHOAN_THU", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class DOT_THU_KHOAN_THU
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int HOC_KY { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    public long ID_DOT_THU { get; set; }

    public long ID_KHOAN_THU { get; set; }

    public double SO_LUONG { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [ForeignKey("ID_DOT_THU")]
    [InverseProperty("DOT_THU_KHOAN_THU")]
    public virtual DOT_THU ID_DOT_THUNavigation { get; set; } = null!;

    [ForeignKey("ID_KHOAN_THU")]
    [InverseProperty("DOT_THU_KHOAN_THU")]
    public virtual KHOAN_THU ID_KHOAN_THUNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("DOT_THU_KHOAN_THU")]
    public virtual TRUONG? ID_TRUONGNavigation { get; set; }

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("DOT_THU_KHOAN_THU")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("DOT_THU_KHOAN_THU")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;
}