// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_TRUONG", "ID_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU_TU_NGUYEN", "MA_KHOI", "ID_HOC_SINH", "MA_HOC_SINH", Name = "IX_KEY", IsUnique = true)]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU_TU_NGUYEN", "MA_KHOI", "MA_NHOM_TUOI_MN", "ID_LOP", "ID_HOC_SINH", "MA_HOC_SINH", Name = "IX_KEY_SO_TRUONG_CAP_NAM_KHOI_ID_DOT_THU_ID_LOP_HOC_SINH", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_SO_TRUONG_CAP_NAM")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_SO_TRUONG_CAP_NAM_HOC_SINH")]
public partial class DOT_THU_TN_CHI_TIET
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public long ID_DOT_THU_TU_NGUYEN { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? SO_TIEN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TIEP_NHAN { get; set; }

    [StringLength(20)]
    public string? MA_HINH_THUC { get; set; }

    public int TRANG_THAI { get; set; }

    [StringLength(500)]
    public string? GHI_CHU { get; set; }

    [StringLength(50)]
    public string? MA_GIAO_DICH { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("DOT_THU_TN_CHI_TIET")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; } = null!;

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("DOT_THU_TN_CHI_TIET")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("DOT_THU_TN_CHI_TIET")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;
}