// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU_TU_NGUYEN", "MA_KHOI", "MA_NHOM_TUOI_MN", "ID_LOP", Name = "IX_DOT_THU_TN_DOI_TUONG_MA_SO_MA_TRUONG_CAP_HOC_NAM_HOC_ID_DOT_THU_TN_KHOI_LOP", IsUnique = true)]
[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU_TU_NGUYEN", "MA_KHOI", "MA_NHOM_TUOI_MN", "ID_LOP", Name = "IX_KEY", IsUnique = true)]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_NAM_SO_TRUONG_CAP")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU_TU_NGUYEN", "ID_LOP", Name = "IX_NAM_SO_TRUONG_CAP_ID_DOT_THU_ID_LOP")]
public partial class DOT_THU_TN_DOI_TUONG
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public long ID_DOT_THU_TU_NGUYEN { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}