// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("GroupUserPGDCode", "PhongGDMA", Name = "IX_KEY", IsUnique = true)]
public partial class GroupUserPGD
{
    [Key]
    public long GroupUserPGDID { get; set; }

    [Required]
    [StringLength(50)]
    public string GroupUserPGDCode { get; set; }

    [Required]
    [StringLength(120)]
    public string GroupUserPGDName { get; set; }

    [StringLength(50)]
    public string SoGDMA { get; set; }

    [StringLength(50)]
    public string PhongGDMA { get; set; }

    public int ISRoot { get; set; }

    public int Status { get; set; }

    [StringLength(120)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [StringLength(120)]
    public string UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(120)]
    public string AuthBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuthAt { get; set; }

    [InverseProperty("GroupUserPGD")]
    public virtual ICollection<GroupUserPGDMenuPGD> GroupUserPGDMenuPGD { get; set; } = new List<GroupUserPGDMenuPGD>();
}