// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MenuPGDID", "GroupUserPGDID", Name = "IX_KEY", IsUnique = true)]
public partial class GroupUserPGDMenuPGD
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal GroupUserPGDMenuPGDID { get; set; }

    public long MenuPGDID { get; set; }

    public long GroupUserPGDID { get; set; }

    public int? IsView { get; set; }

    public int IsAdd { get; set; }

    public int IsEdit { get; set; }

    public int IsDelete { get; set; }

    public int IsUpload { get; set; }

    public int IsAuth { get; set; }

    [StringLength(120)]
    public string? CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [StringLength(120)]
    public string? UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(120)]
    public string? AuthBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuthAt { get; set; }

    [ForeignKey("GroupUserPGDID")]
    [InverseProperty("GroupUserPGDMenuPGD")]
    public virtual GroupUserPGD GroupUserPGD { get; set; } = null!;

    [ForeignKey("MenuPGDID")]
    [InverseProperty("GroupUserPGDMenuPGD")]
    public virtual MenuPGD MenuPGD { get; set; } = null!;
}