// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("GroupUserSGDCode", "SoGDMA", Name = "IX_KEY", IsUnique = true)]
public partial class GroupUserSGD
{
    [Key]
    public long GroupUserSGDID { get; set; }

    [Required]
    [StringLength(50)]
    public string GroupUserSGDCode { get; set; }

    [Required]
    [StringLength(120)]
    public string GroupUserSGDName { get; set; }

    [StringLength(50)]
    public string SoGDMA { get; set; }

    public int ISRoot { get; set; }

    public int Status { get; set; }

    [StringLength(120)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [StringLength(120)]
    public string UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(120)]
    public string AuthBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuthAt { get; set; }

    [InverseProperty("GroupUserSGD")]
    public virtual ICollection<GroupUserSGDMenuSGD> GroupUserSGDMenuSGD { get; set; } = new List<GroupUserSGDMenuSGD>();
}