// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MenuSGDID", "GroupUserSGDID", Name = "IX_KEY", IsUnique = true)]
public partial class GroupUserSGDMenuSGD
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal GroupUserSGDMenuSGDID { get; set; }

    public long MenuSGDID { get; set; }

    public long GroupUserSGDID { get; set; }

    public int? IsView { get; set; }

    public int Ithuphidd { get; set; }

    public int IsEdit { get; set; }

    public int IsDelete { get; set; }

    public int IsUpload { get; set; }

    public int Ithuphiuth { get; set; }

    [StringLength(120)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [StringLength(120)]
    public string UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(120)]
    public string AuthBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuthAt { get; set; }

    [ForeignKey("GroupUserSGDID")]
    [InverseProperty("GroupUserSGDMenuSGD")]
    public virtual GroupUserSGD GroupUserSGD { get; set; }

    [ForeignKey("MenuSGDID")]
    [InverseProperty("GroupUserSGDMenuSGD")]
    public virtual MenuSGD MenuSGD { get; set; }
}