// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_GD", "ID_TRUONG", "MA_NAM_HOC", "ID_DOT_THU", "ID_LOP", "ID_HOC_SINH", "ID_PHIEU_THU", "MA_CAP_HOC", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU", Name = "IX_NAM_SO_CAP_TRUONG_DOT_THU")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class HOA_DON_DIEN_TU
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_CAP_HOC { get; set; }

    public int MA_NAM_HOC { get; set; }

    public long? ID_DOT_THU { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_KHOI { get; set; }

    [StringLength(50)]
    public string MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_DON_VI { get; set; }

    public long? ID_PHIEU_THU { get; set; }

    [StringLength(50)]
    public string ID_HOA_DON { get; set; }

    [StringLength(50)]
    public string MA_LOAI_HOA_DON { get; set; }

    [StringLength(50)]
    public string MAU_SO { get; set; }

    [StringLength(50)]
    public string KY_HIEU { get; set; }

    [StringLength(50)]
    public string SO_HOA_DON { get; set; }

    [StringLength(50)]
    public string SO_BIEN_LAI { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_GIAN_XUAT_HD { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_GIAN_HUY_HD { get; set; }

    public int? TRANG_THAI { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}