// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("ID_HOC_SINH", "ID_DM_MIEN_GIAM", Name = "IX_HOC_SINH_MIEN_GIAM_UNIQUE", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class HOC_SINH_MIEN_GIAM
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_CAP_HOC { get; set; }

    public int MA_NAM_HOC { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_KHOI { get; set; }

    [StringLength(50)]
    public string MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }

    public long ID_DM_MIEN_GIAM { get; set; }

    [StringLength(250)]
    public string GHI_CHU { get; set; }

    public int IS_AUTO { get; set; }

    [StringLength(50)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(50)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_BAT_DAU { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_KET_THUC { get; set; }

    [ForeignKey("ID_DM_MIEN_GIAM")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual DM_MIEN_GIAM ID_DM_MIEN_GIAMNavigation { get; set; }

    [ForeignKey("ID_HOC_SINH")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual HOC_SINH ID_HOC_SINHNavigation { get; set; }

    [ForeignKey("ID_LOP")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual LOP ID_LOPNavigation { get; set; }

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; }

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; }

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("HOC_SINH_MIEN_GIAM")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; }
}