// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("KEY_SYSTEM", Name = "IDX_HOC_SINH_KEY_SYSTEM")]
[Index("MA_SO_DINH_DANH_CA_NHAN", Name = "IDX_HOC_SINH_MA_SO_DINH_DANH_CA_NHAN")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_NAM_HOC", "MA_CAP_HOC", "MA_SO_DINH_DANH_CA_NHAN", Name = "IDX_HOC_SINH_MA_SO_DINH_DANH_CA_NHAN_2")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_NAM_HOC", Name = "IDX_MA_SO_NAM_HOC_MA_TRUONG")]
[Index("MA", Name = "IX_HOC_SINH")]
[Index("API_MA_BO", Name = "IX_HOC_SINH_MA_BO")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_NAM_HOC", "MA_CAP_HOC", "MA", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("MA_SO_GD", "ID_TRUONG", "MA_NAM_HOC", "MA_CAP_HOC", Name = "IX_SO_NAM_CAP_ID_TRUONG")]
public partial class HOC_SINH
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string MA_PHONG_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_TRUONG { get; set; }

    public int MA_NAM_HOC { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_CAP_HOC { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_KHOI { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; }

    [Required]
    [StringLength(20)]
    public string MA { get; set; }

    [Required]
    [StringLength(150)]
    public string HO_TEN { get; set; }

    [Column(TypeName = "date")]
    public DateTime NGAY_SINH { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_GIOI_TINH { get; set; }

    [StringLength(20)]
    public string MA_DAN_TOC { get; set; }

    [StringLength(20)]
    public string MA_QUOC_TICH { get; set; }

    [StringLength(20)]
    public string MA_KHU_VUC { get; set; }

    [StringLength(20)]
    public string MA_LOAI_KHUYET_TAT { get; set; }

    [StringLength(20)]
    public string MA_TINH { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HUYEN { get; set; }

    [StringLength(20)]
    public string MA_HUYEN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_XA { get; set; }

    [StringLength(20)]
    public string MA_XA { get; set; }

    [StringLength(500)]
    public string THON_XOM { get; set; }

    [StringLength(500)]
    public string NOI_SINH { get; set; }

    [StringLength(500)]
    public string CHO_O_HIEN_NAY { get; set; }

    [StringLength(500)]
    public string TEN_CHA { get; set; }

    public int? NAM_SINH_CHA { get; set; }

    [StringLength(250)]
    public string NGHE_NGHIEP_CHA { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_CHA { get; set; }

    [StringLength(150)]
    public string TEN_ME { get; set; }

    public int? NAM_SINH_ME { get; set; }

    [StringLength(250)]
    public string NGHE_NGHIEP_ME { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_ME { get; set; }

    [StringLength(150)]
    public string TEN_NGUOI_DD { get; set; }

    public int? NAM_SINH_NGUOI_DO_DAU { get; set; }

    [StringLength(250)]
    public string NGHE_NGHIEP_NGUOI_DD { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_NGUOI_DD { get; set; }

    [StringLength(50)]
    public string DIEN_THOAI_LIEN_HE { get; set; }

    [StringLength(300)]
    public string URL_ANH_DAI_DIEN { get; set; }

    [StringLength(500)]
    public string DAN_TOC_THEO_GIAY_KHAI_SINH { get; set; }

    [StringLength(20)]
    public string MA_CONG_DAN { get; set; }

    [StringLength(500)]
    public string QUE_QUAN { get; set; }

    [StringLength(20)]
    public string MA_DIA_PHUONG { get; set; }

    [StringLength(20)]
    public string MA_TON_GIAO { get; set; }

    public int? IS_KHUYET_TAT_KHONG_DANH_GIA { get; set; }

    public int? IS_HO_NGHEO { get; set; }

    public int? IS_VUNG_KK { get; set; }

    public int? IS_ME_DT { get; set; }

    public int? IS_CHA_DT { get; set; }

    [StringLength(20)]
    public string MA_DIEN_CHINH_thuphiCH { get; set; }

    public int? IS_MIEN_HOC_PHI { get; set; }

    public int? IS_GIAM_HOC_PHI { get; set; }

    public int? IS_HO_TRO_CHI_PHI_HOC_TAP { get; set; }

    public int? IS_CAP_TIEN_HANG_THANG { get; set; }

    public int? IS_CAP_GAO { get; set; }

    public int? IS_HO_TRO_NHA_O { get; set; }

    public int? IS_HOC_CTGD_CUA_BO { get; set; }

    public int? IS_HO_TRO_AN_TRUA { get; set; }

    public int? IS_HOC_LOP_MG_5T { get; set; }

    public int? IS_TUYEN_MOI_MN { get; set; }

    [StringLength(20)]
    public string MA_LOAI_BO_THUONG_BINH { get; set; }

    [StringLength(20)]
    public string MA_SO_DINH_DANH_CA_NHAN { get; set; }

    public int? IS_CO_CHIP_CCCD { get; set; }

    [StringLength(20)]
    public string MA_TRANG_THAI_K1 { get; set; }

    [StringLength(20)]
    public string MA_TRANG_THAI_K2 { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_TRANG_THAI_HIEN_TAI { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NGAY_TRANG_THAI { get; set; }

    public int? IS_DANG_HOC_K1 { get; set; }

    public int? IS_DANG_HOC_K2 { get; set; }

    public int? THU_TU { get; set; }

    [StringLength(50)]
    public string API_MA_HCM { get; set; }

    [StringLength(50)]
    public string API_MA_BO { get; set; }

    [StringLength(400)]
    public string KEY_SYSTEM { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    public int? IS_QLTP { get; set; }

    [StringLength(250)]
    public string GHI_CHU { get; set; }

    [StringLength(50)]
    public string CMND { get; set; }

    [StringLength(150)]
    public string NOI_CAP { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NGAY_CAP { get; set; }

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; } = new List<DIEM_DANH_HS_NHOM>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU> DIEM_DANH_KHOAN_THU { get; set; } = new List<DIEM_DANH_KHOAN_THU>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_KY> DIEM_DANH_KHOAN_THU_KY { get; set; } = new List<DIEM_DANH_KHOAN_THU_KY>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_NAM> DIEM_DANH_KHOAN_THU_NAM { get; set; } = new List<DIEM_DANH_KHOAN_THU_NAM>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DK_KHOAN_THU_SL_DG> DK_KHOAN_THU_SL_DG { get; set; } = new List<DK_KHOAN_THU_SL_DG>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DK_KHOAN_THU_TN> DK_KHOAN_THU_TN { get; set; } = new List<DK_KHOAN_THU_TN>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<DOT_THU_DOI_TUONG> DOT_THU_DOI_TUONG { get; set; } = new List<DOT_THU_DOI_TUONG>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; } = new List<HOC_SINH_MIEN_GIAM>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<KHOAN_THU_DOI_TUONG> KHOAN_THU_DOI_TUONG { get; set; } = new List<KHOAN_THU_DOI_TUONG>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; } = new List<LICH_SU_THANH_TOAN>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; } = new List<PHIEU_THU>();

    [InverseProperty("ID_HOC_SINHNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}