// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_KHOAN_THU", "ID_DM_MIEN_GIAM", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class KHOAN_THU_MIEN_GIAM
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public long ID_KHOAN_THU { get; set; }

    public long ID_DM_MIEN_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? SO_TIEN_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? PHAN_TRAM_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? SO_TIEN_GIAM_TOI_DA { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [ForeignKey("ID_DM_MIEN_GIAM")]
    [InverseProperty("KHOAN_THU_MIEN_GIAM")]
    public virtual DM_MIEN_GIAM ID_DM_MIEN_GIAMNavigation { get; set; } = null!;

    [ForeignKey("ID_KHOAN_THU")]
    [InverseProperty("KHOAN_THU_MIEN_GIAM")]
    public virtual KHOAN_THU ID_KHOAN_THUNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("KHOAN_THU_MIEN_GIAM")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; } = null!;

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("KHOAN_THU_MIEN_GIAM")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("KHOAN_THU_MIEN_GIAM")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;
}