// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class LICH_SU_THANH_TOAN
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_CAP_HOC { get; set; }

    public int MA_NAM_HOC { get; set; }

    public int HOC_KY { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_KHOI { get; set; }

    [StringLength(50)]
    public string MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_LOP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_HOC_SINH { get; set; }

    [StringLength(150)]
    public string TAI_KHOAN_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string DOI_TAC_THANH_TOAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_DIEM_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string GHI_CHU_THANH_TOAN { get; set; }

    public long? ID_KHOAN_THU { get; set; }

    public int? SO_NGAY_THUA { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? DON_GIA { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal SO_TIEN { get; set; }

    public long? ID_LSTT { get; set; }

    public int IS_SU_DUNG { get; set; }

    public int LOAI_SU_DUNG { get; set; }

    public long? ID_DOT_THU { get; set; }

    public long? ID_PHIEU_THU { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(150)]
    public string DOI_TUONG_THUC_HIEN { get; set; }

    [ForeignKey("ID_DOT_THU")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual DOT_THU ID_DOT_THUNavigation { get; set; }

    [ForeignKey("ID_HOC_SINH")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual HOC_SINH ID_HOC_SINHNavigation { get; set; }

    [ForeignKey("ID_KHOAN_THU")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual KHOAN_THU ID_KHOAN_THUNavigation { get; set; }

    [ForeignKey("ID_LOP")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual LOP ID_LOPNavigation { get; set; }

    [ForeignKey("ID_PHIEU_THU")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual PHIEU_THU ID_PHIEU_THUNavigation { get; set; }

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; }

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; }

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("LICH_SU_THANH_TOAN")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; }
}