// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_MA_SO_GD_MA_TRUONG_MA_CAP_HOC_MA_NAM_HOC_ET_ID_TRUONG_NGAY_THU")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("NGAY_THU", Name = "IX_NGAY_THU")]
[Index("MA_SO_GD", "ID_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "SO_ID_TRUONG_CAP_HOC_NAM_HOC")]
public partial class LICH_SU_THU_TIEN
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int KIEU_THANH_TOAN { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal SO_TIEN { get; set; }

    public int? LOAI_HOAN_TRA { get; set; }

    [StringLength(150)]
    public string? NGUOI_THU { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_THU { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(150)]
    public string? TAI_KHOAN_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string? DOI_TAC_THANH_TOAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_DIEM_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string? GHI_CHU_THANH_TOAN { get; set; }

    [InverseProperty("ID_LSTTNavigation")]
    public virtual ICollection<LICH_SU_THU_TIEN_CT> LICH_SU_THU_TIEN_CT { get; set; } = new List<LICH_SU_THU_TIEN_CT>();
}