// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU", Name = "IX_ID_LSTT_ID_PHIEU_THU")]
[Index("ID_PHIEU_THU", "ID_PHIEU_THU_CT", Name = "IX_ID_PHIEU_THU_ID_PHIEU_THU_CT_EXT_ID_LSTT_SO_TIEN")]
[Index("ID_LSTT", "MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "HOC_KY", "THANG", "NAM", "MA_KHOI", "MA_NHOM_TUOI_MN", "ID_LOP", "MA_LOP", "ID_HOC_SINH", "MA_HOC_SINH", "ID_DOT_THU", "ID_KHOAN_THU", "LOAI_CT", "ID_PHIEU_THU_CT", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_SO_THU_VA_THANH_TOAN")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_PHIEU_THU", Name = "IX_SO_TRUONG_CAP_NAM_PHIEU")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_KHOAN_THU", Name = "MA_SO_GD_MA_TRUONG_MA_CAP_HOC_MA_NAM_HOC_ID_KHOAN_THU_ET")]
public partial class LICH_SU_THU_TIEN_CT
{
    [Key]
    public long ID { get; set; }

    public long ID_LSTT { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int HOC_KY { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    public long ID_PHIEU_THU { get; set; }

    public long ID_DOT_THU { get; set; }

    public long ID_KHOAN_THU { get; set; }

    [StringLength(250)]
    public string? NOI_DUNG { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal SO_TIEN { get; set; }

    public int LOAI_CT { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public long? ID_PHIEU_THU_CT { get; set; }

    [ForeignKey("ID_LSTT")]
    [InverseProperty("LICH_SU_THU_TIEN_CT")]
    public virtual LICH_SU_THU_TIEN ID_LSTTNavigation { get; set; } = null!;
}