// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_HOAN_TIEN", Name = "IX_KEY", IsUnique = true)]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_NAM_SO_CAP_TRUONG")]
public partial class LICH_SU_HOAN_TIEN_CONG_THANH_TOAN
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    [StringLength(250)]
    public string? TEN_HOC_SINH { get; set; }

    [StringLength(200)]
    public string MA_GIAO_DICH { get; set; } = null!;

    [Column(TypeName = "numeric(18, 2)")]
    public decimal TONG_TIEN { get; set; }

    [StringLength(20)]
    public string PHUONG_THUC_THANH_TOAN { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime THOI_GIAN_GIAO_DICH { get; set; }

    [StringLength(200)]
    public string MA_HOAN_TIEN { get; set; } = null!;

    public int TRANG_THAI_HOAN_TIEN { get; set; }

    [StringLength(200)]
    public string? GHI_CHU_HOAN_TIEN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime THOI_GIAN_HOAN_TIEN { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? IP_TAO { get; set; }
}