// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", "MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "TEN", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
public partial class LOP
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string? MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string? MA_PHONG_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [StringLength(20)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string? MA { get; set; }

    public int MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string? MA_CAP_HOC { get; set; }

    [StringLength(20)]
    public string? MA_GIAO_VIEN_CHU_NHIEM { get; set; }

    [StringLength(20)]
    public string? MA_KIEU_LOP { get; set; }

    [StringLength(20)]
    public string? MA_KHOI { get; set; }

    [StringLength(20)]
    public string? MA_PHAN_BAN { get; set; }

    [StringLength(20)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [StringLength(50)]
    public string? TEN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_GIAO_VIEN_CHU_NHIEM { get; set; }

    public int? TRANG_THAI { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_GIAO_VIEN_CHU_NHIEM_KY2 { get; set; }

    public int TRANG_THAI_KY2 { get; set; }

    [StringLength(50)]
    public string? API_MA_HCM { get; set; }

    public Guid MA_GUID { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    public int? IS_QLTP { get; set; }

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; } = new List<DIEM_DANH_HS_NHOM>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU> DIEM_DANH_KHOAN_THU { get; set; } = new List<DIEM_DANH_KHOAN_THU>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_KY> DIEM_DANH_KHOAN_THU_KY { get; set; } = new List<DIEM_DANH_KHOAN_THU_KY>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_NAM> DIEM_DANH_KHOAN_THU_NAM { get; set; } = new List<DIEM_DANH_KHOAN_THU_NAM>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DK_KHOAN_THU_SL_DG> DK_KHOAN_THU_SL_DG { get; set; } = new List<DK_KHOAN_THU_SL_DG>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DK_KHOAN_THU_TN> DK_KHOAN_THU_TN { get; set; } = new List<DK_KHOAN_THU_TN>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<DOT_THU_DOI_TUONG> DOT_THU_DOI_TUONG { get; set; } = new List<DOT_THU_DOI_TUONG>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; } = new List<HOC_SINH_MIEN_GIAM>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<KHOAN_THU_DOI_TUONG> KHOAN_THU_DOI_TUONG { get; set; } = new List<KHOAN_THU_DOI_TUONG>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH> KHOA_DIEM_DANH { get; set; } = new List<KHOA_DIEM_DANH>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_KY> KHOA_DIEM_DANH_KY { get; set; } = new List<KHOA_DIEM_DANH_KY>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_NAM> KHOA_DIEM_DANH_NAM { get; set; } = new List<KHOA_DIEM_DANH_NAM>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; } = new List<LICH_SU_THANH_TOAN>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; } = new List<PHIEU_THU>();

    [InverseProperty("ID_LOPNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}