// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA_SO_GD", "ID_DM_MIEN_GIAM_SO", "ID_CH_HS", "GIA_TRI_HS", Name = "IX_KEY", IsUnique = true)]
public partial class MAP_MIEN_GIAM_HS_SO
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    public long ID_DM_MIEN_GIAM_SO { get; set; }

    public int ID_CH_HS { get; set; }

    [StringLength(50)]
    public string GIA_TRI_HS { get; set; } = null!;

    [StringLength(250)]
    public string? TEN_GIA_TRI { get; set; }

    [ForeignKey("ID_CH_HS")]
    [InverseProperty("MAP_MIEN_GIAM_HS_SO")]
    public virtual CH_HS ID_CH_HSNavigation { get; set; } = null!;

    [ForeignKey("ID_DM_MIEN_GIAM_SO")]
    [InverseProperty("MAP_MIEN_GIAM_HS_SO")]
    public virtual DM_MIEN_GIAM_SO ID_DM_MIEN_GIAM_SONavigation { get; set; } = null!;
}