// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class MenuPGD
{
    [Key]
    public long MenuPGDID { get; set; }

    public long? ParentID { get; set; }

    [StringLength(100)]
    public string MenuPGDCode { get; set; }

    public int? LevelItem { get; set; }

    [Required]
    [StringLength(120)]
    public string MenuPGDName { get; set; }

    [StringLength(150)]
    public string Icon { get; set; }

    [StringLength(150)]
    public string Link { get; set; }

    public int? TypeHelp { get; set; }

    [StringLength(250)]
    public string DesHelp { get; set; }

    [StringLength(150)]
    public string LinkYoutube { get; set; }

    [StringLength(20)]
    public string Order { get; set; }

    public int IsView { get; set; }

    public int Status { get; set; }

    [StringLength(120)]
    public string CreateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreateAt { get; set; }

    [StringLength(120)]
    public string UpdateBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UpdateAt { get; set; }

    [StringLength(120)]
    public string AuthBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? AuthAt { get; set; }

    [StringLength(120)]
    public string MenuPGDNameEG { get; set; }

    [InverseProperty("MenuPGD")]
    public virtual ICollection<GroupUserPGDMenuPGD> GroupUserPGDMenuPGD { get; set; } = new List<GroupUserPGDMenuPGD>();
}