// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class NAM_HOC
{
    [Key]
    public int MA { get; set; }

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [StringLength(20)]
    public string MA_SOURCE { get; set; } = null!;

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<CAU_HINH_PHIEU_THU> CAU_HINH_PHIEU_THU { get; set; } = new List<CAU_HINH_PHIEU_THU>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; } = new List<DIEM_DANH_HS_NHOM>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU> DIEM_DANH_KHOAN_THU { get; set; } = new List<DIEM_DANH_KHOAN_THU>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_KY> DIEM_DANH_KHOAN_THU_KY { get; set; } = new List<DIEM_DANH_KHOAN_THU_KY>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_NAM> DIEM_DANH_KHOAN_THU_NAM { get; set; } = new List<DIEM_DANH_KHOAN_THU_NAM>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DK_KHOAN_THU_SL_DG> DK_KHOAN_THU_SL_DG { get; set; } = new List<DK_KHOAN_THU_SL_DG>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DK_KHOAN_THU_TN> DK_KHOAN_THU_TN { get; set; } = new List<DK_KHOAN_THU_TN>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DOT_THU> DOT_THU { get; set; } = new List<DOT_THU>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DOT_THU_DOI_TUONG> DOT_THU_DOI_TUONG { get; set; } = new List<DOT_THU_DOI_TUONG>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DOT_THU_KHOAN_THU> DOT_THU_KHOAN_THU { get; set; } = new List<DOT_THU_KHOAN_THU>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<DOT_THU_TN_CHI_TIET> DOT_THU_TN_CHI_TIET { get; set; } = new List<DOT_THU_TN_CHI_TIET>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; } = new List<HOC_SINH_MIEN_GIAM>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<KHOAN_THU_DOI_TUONG> KHOAN_THU_DOI_TUONG { get; set; } = new List<KHOAN_THU_DOI_TUONG>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<KHOAN_THU_MIEN_GIAM> KHOAN_THU_MIEN_GIAM { get; set; } = new List<KHOAN_THU_MIEN_GIAM>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH> KHOA_DIEM_DANH { get; set; } = new List<KHOA_DIEM_DANH>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_KY> KHOA_DIEM_DANH_KY { get; set; } = new List<KHOA_DIEM_DANH_KY>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_NAM> KHOA_DIEM_DANH_NAM { get; set; } = new List<KHOA_DIEM_DANH_NAM>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; } = new List<LICH_SU_THANH_TOAN>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; } = new List<PHIEU_THU>();

    [InverseProperty("MA_NAM_HOCNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}