// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class NGAY_TRONG_NAM
{
    [Key]
    [Column(TypeName = "date")]
    public DateTime NGAY_THANG_NAM { get; set; }

    public int? NAM { get; set; }

    public int? THANG { get; set; }

    public int? NGAY { get; set; }

    public int? THU { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NGAY_LAM_VIEC_TIEP { get; set; }
}