// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("TEN_DANG_NHAP", "MA_CAP_DON_VI", "MA_SO_GD", "MA_PHONG_GD", "MA_TRUONG", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", Name = "IX_NGUOI_DUNG")]
[Index("MA_NHAN_SU", Name = "IX_NGUOI_DUNG_1")]
[Index("MA_CAP_DON_VI", Name = "IX_NGUOI_DUNG_10")]
[Index("MA_SO_GD", Name = "IX_NGUOI_DUNG_2")]
[Index("MA_PHONG_GD", Name = "IX_NGUOI_DUNG_3")]
[Index("MA_TRUONG", Name = "IX_NGUOI_DUNG_4")]
[Index("TEN_DANG_NHAP", Name = "IX_NGUOI_DUNG_5")]
[Index("MAT_KHAU", Name = "IX_NGUOI_DUNG_6")]
[Index("TRANG_THAI", Name = "IX_NGUOI_DUNG_7")]
[Index("IS_ROOT", Name = "IX_NGUOI_DUNG_8")]
[Index("IS_ROOT_SYS", Name = "IX_NGUOI_DUNG_9")]
public partial class NGUOI_DUNG
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(20)]
    public string? MA_NHAN_SU { get; set; }

    [StringLength(50)]
    public string TEN_DANG_NHAP { get; set; } = null!;

    public int? MA_NAM_HOC { get; set; }

    [StringLength(250)]
    public string? TEN_HIEN_THI { get; set; }

    [StringLength(250)]
    public string? MAT_KHAU { get; set; }

    [StringLength(50)]
    public string? MA_NHOM_QUYEN { get; set; }

    [StringLength(20)]
    public string? MA_CAP_DON_VI { get; set; }

    [StringLength(20)]
    public string? MA_SO_GD { get; set; }

    [StringLength(20)]
    public string? MA_PHONG_GD { get; set; }

    [StringLength(20)]
    public string? MA_TRUONG { get; set; }

    public int? IS_ROOT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    public int? IS_ROOT_SYS { get; set; }

    public int? TRANG_THAI { get; set; }

    public int? IS_UPDATE { get; set; }

    [StringLength(250)]
    public string? EMAIL { get; set; }

    [StringLength(250)]
    public string? DIEN_THOAI_DI_DONG { get; set; }

    [StringLength(150)]
    public string? HO_TEN { get; set; }

    [StringLength(250)]
    public string? CHUC_VU_PHONG_BAN { get; set; }

    [StringLength(200)]
    public string? connectionId { get; set; }

    [StringLength(20)]
    public string? ip { get; set; }

    [StringLength(250)]
    public string? MAT_KHAU_BACKUP { get; set; }

    public int? IS_MASTER_ROOT_SYS { get; set; }

    [StringLength(100)]
    public string? MA_KHOI_PHUC_MAT_KHAU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LAST_LOGIN { get; set; }

    public Guid? VERSION { get; set; }
}