// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("ID_NHAN_SU", Name = "IX_NHAN_SU_LOP_CHU_NHIEM_ID_NHAN_SU")]
[Index("ID_TRUONG", Name = "IX_NHAN_SU_LOP_CHU_NHIEM_ID_TRUONG")]
[Index("MA_NAM_HOC", Name = "IX_NHAN_SU_LOP_CHU_NHIEM_MA_NAM_HOC")]
[Index("MA_SO_GD", Name = "IX_NHAN_SU_LOP_CHU_NHIEM_MA_SOGD")]
[Index("MA_TRUONG", Name = "IX_NHAN_SU_LOP_CHU_NHIEM_MA_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_PHONG_GD", "MA_PHONG_GD", "ID_TRUONG", "MA_TRUONG", "ID_LOP", "ID_NHAN_SU", "HOC_KY", Name = "NHAN_SU_LOP_CHU_NHIEM_MA_NAM_HOC_MA_SO_GD_ID_PHONG_GD_MA_PHONG_GD_ID_TRUONG_MA_TRUONG_ID_LOP_ID_NHAN_SU", IsUnique = true)]
public partial class NHAN_SU_LOP_CHU_NHIEM
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    public int MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string? MA_PHONG_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(20)]
    public string MA_TRUONG { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_NHAN_SU { get; set; }

    public int HOC_KY { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }
}