// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", "ID_TRUONG", "MA_TRUONG", "MA_NAM_HOC", "ID_PHONG_GD", "MA_SO_GD", Name = "IX_IDTRUONG_MAGV", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
public partial class NHAN_SU
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [StringLength(150)]
    public string? HO_TEN { get; set; }

    [StringLength(20)]
    public string? MA { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NGAY_SINH { get; set; }

    [StringLength(500)]
    public string? NOI_SINH { get; set; }

    [StringLength(20)]
    public string? MA_CAP_DON_VI { get; set; }

    public int? MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string? MA_SO_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string? MA_PHONG_GD { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_TRUONG { get; set; }

    [StringLength(20)]
    public string? MA_TRUONG { get; set; }

    [StringLength(20)]
    public string? MA_TINH { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HUYEN { get; set; }

    [StringLength(20)]
    public string? MA_HUYEN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_XA { get; set; }

    [StringLength(20)]
    public string? MA_XA { get; set; }

    [StringLength(20)]
    public string? MA_CAP_HOC { get; set; }

    [StringLength(200)]
    public string SO_CMTND { get; set; } = null!;

    [StringLength(500)]
    public string? NOI_CAP { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NGAY_CAP { get; set; }

    [StringLength(300)]
    public string? URL_ANH_DAI_DIEN { get; set; }

    [StringLength(50)]
    public string? DI_DONG { get; set; }

    [StringLength(150)]
    public string? EMAIL { get; set; }

    [StringLength(20)]
    public string? MA_GIOI_TINH { get; set; }

    [StringLength(20)]
    public string? MA_DAN_TOC { get; set; }

    [StringLength(20)]
    public string? MA_TON_GIAO { get; set; }

    [StringLength(20)]
    public string? MA_NUOC { get; set; }

    [StringLength(20)]
    public string? MA_LOAI_CAN_BO { get; set; }

    [StringLength(20)]
    public string? MA_NHOM_CAN_BO { get; set; }

    [StringLength(20)]
    public string? MA_PHONG_BAN { get; set; }

    public int? IS_MN { get; set; }

    public int? IS_C1 { get; set; }

    public int? IS_C2 { get; set; }

    public int? IS_C3 { get; set; }

    public int? IS_GDTX { get; set; }

    [StringLength(50)]
    public string? API_MA_BO { get; set; }

    [StringLength(20)]
    public string? MA_SO_DINH_DANH_CA_NHAN { get; set; }

    public int? IS_CO_CHIP_CCCD { get; set; }

    [StringLength(10)]
    public string? MA_CAP_HOC_CHINH { get; set; }

    [StringLength(20)]
    public string? MA_TRANG_THAI_CAN_BO { get; set; }

    public int? IS_TRANG_THAI_KY_1 { get; set; }

    public int? IS_TRANG_THAI_KY_2 { get; set; }

    public int? TRANG_THAI { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    [StringLength(200)]
    public string? TEN { get; set; }
}