// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "TEN", Name = "IX_KEY", IsUnique = true)]
public partial class NHOM_DIEM_DANH
{
    [Key]
    public long ID { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Required]
    [StringLength(50)]
    public string MA_CAP_HOC { get; set; }

    [Required]
    [StringLength(150)]
    public string TEN { get; set; }

    public int THU_TU { get; set; }

    [StringLength(250)]
    public string GHI_CHU { get; set; }

    public int TRANG_THAI { get; set; }

    [StringLength(150)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [InverseProperty("ID_NHOM_DIEM_DANHNavigation")]
    public virtual ICollection<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; } = new List<DIEM_DANH_HS_NHOM>();
}