// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("IS_CHOT", Name = "IX_IS_CHOT")]
[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "HOC_KY", "THANG", "NAM", "ID_DOT_THU", "MA_KHOI", "ID_HOC_SINH", "MA_HOC_SINH", Name = "IX_KEY", IsUnique = true)]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "HOC_KY", "THANG", "NAM", Name = "IX_MA_SO_GD_MA_TRUONG_MA_CAP_HOC_MA_NAM_HOC_HOC_KY_THANG_NAM")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_CAP_HOC", "MA_TRUONG", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU", Name = "IX_NAM_SO_CAP_TRUONG_DOT_THU")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", "IS_CHOT", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH_CHOT")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("THANG", Name = "IX_THANG")]
[Index("THANG", "ID_DOT_THU", Name = "IX_THANG_DOT_THU")]
public partial class PHIEU_THU
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int HOC_KY { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    public long ID_DOT_THU { get; set; }

    [StringLength(50)]
    public string? MA_PHIEU_THU { get; set; }

    [StringLength(50)]
    public string? TIEN_TO_PHIEU_THU { get; set; }

    public long? STT_PHIEU_THU { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    [StringLength(250)]
    public string? TEN_HOC_SINH { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal TONG_TIEN_PHAI_THU { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal TIEN_DA_THU { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal CON_LAI { get; set; }

    public int IS_DA_THANH_TOAN { get; set; }

    public int KIEU_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string? TAI_KHOAN_THANH_TOAN { get; set; }

    [StringLength(150)]
    public string? DOI_TAC_THANH_TOAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? THOI_DIEM_THANH_TOAN { get; set; }

    [StringLength(250)]
    public string? ANH_THANH_TOAN_LOCAL { get; set; }

    [StringLength(250)]
    public string? ANH_THANH_TOAN_DO { get; set; }

    [StringLength(250)]
    public string? GHI_CHU_THANH_TOAN { get; set; }

    public int IS_CHOT { get; set; }

    public int IS_EDITED { get; set; }

    [StringLength(500)]
    public string? FILE_NAME { get; set; }

    [StringLength(500)]
    public string? FILE_PATH_LOCAL { get; set; }

    [StringLength(500)]
    public string? FILE_PATH_DO { get; set; }

    public int IS_UPLOAD_DO { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public long? STT_PHIEU_THU_TRUONG { get; set; }

    [StringLength(150)]
    public string? NGUOI_CHOT { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_CHOT { get; set; }

    [StringLength(150)]
    public string? NGUOI_THANH_TOAN { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_THANH_TOAN { get; set; }

    [StringLength(250)]
    public string? MA_GIAO_DICH { get; set; }

    [ForeignKey("ID_HOC_SINH")]
    [InverseProperty("PHIEU_THU")]
    public virtual HOC_SINH ID_HOC_SINHNavigation { get; set; } = null!;

    [ForeignKey("ID_LOP")]
    [InverseProperty("PHIEU_THU")]
    public virtual LOP ID_LOPNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("PHIEU_THU")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; } = null!;

    [InverseProperty("ID_PHIEU_THUNavigation")]
    public virtual ICollection<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; } = new List<LICH_SU_THANH_TOAN>();

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("PHIEU_THU")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("PHIEU_THU")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;

    [InverseProperty("ID_PHIEU_THUNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}