// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("ID_PHIEU_THU", Name = "IX_ID_PHIEU_THU_DA_THU_CON_LAI")]
[Index("ID_PHIEU_THU", Name = "IX_ID_PHIEU_THU_EXT_ID_KHOAN_THU_DA_THU_CON_LAI")]
[Index("MA_SO_GD", "ID_TRUONG", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "HOC_KY", "THANG", "NAM", "ID_DOT_THU", "MA_KHOI", "ID_HOC_SINH", "MA_HOC_SINH", "ID_PHIEU_THU", "LOAI_CT", "ID_KHOAN_THU", "ID_LICH_SU_THANH_TOAN", Name = "IX_KEY", IsUnique = true)]
[Index("LOAI_CT", Name = "IX_LOAI_CT")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "CON_LAI", Name = "IX_MA_SO_GD_MA_TRUONG_MA_CAP_HOC_MA_NAM_HOC_CON_LAI_EXT")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU", Name = "IX_MA_SO_GD_MA_TRUONG_MA_CAP_HOC_MA_NAM_HOC_ID_DOT_THU_EXT")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", Name = "IX_NAM_SO_CAP_TRUONG")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_DOT_THU", Name = "IX_NAM_SO_CAP_TRUONG_DOT_THU")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "MA_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_HOC_SINH")]
[Index("MA_SO_GD", "MA_TRUONG", "MA_CAP_HOC", "MA_NAM_HOC", "ID_HOC_SINH", Name = "IX_NAM_SO_CAP_TRUONG_ID_HOC_SINH")]
[Index("MA_NAM_HOC", "MA_SO_GD", "ID_TRUONG", Name = "IX_NAM_SO_ID_TRUONG")]
[Index("MA_NAM_HOC", "MA_SO_GD", "MA_TRUONG", Name = "IX_NAM_SO_TRUONG")]
[Index("ID_PHIEU_THU", "LOAI_CT", "ID_KHOAN_THU", Name = "IX_PHIEU_THU_LOAI_KHOAN")]
public partial class PHIEU_THU_CT
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_TRUONG { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; } = null!;

    [StringLength(50)]
    public string MA_CAP_HOC { get; set; } = null!;

    public int MA_NAM_HOC { get; set; }

    public int HOC_KY { get; set; }

    public int THANG { get; set; }

    public int NAM { get; set; }

    public long ID_DOT_THU { get; set; }

    [StringLength(50)]
    public string MA_KHOI { get; set; } = null!;

    [StringLength(50)]
    public string? MA_NHOM_TUOI_MN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_LOP { get; set; }

    [StringLength(50)]
    public string MA_LOP { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_HOC_SINH { get; set; }

    [StringLength(50)]
    public string MA_HOC_SINH { get; set; } = null!;

    public long ID_PHIEU_THU { get; set; }

    public int LOAI_CT { get; set; }

    public long? ID_KHOAN_THU { get; set; }

    public long? ID_DM_MIEN_GIAM { get; set; }

    [StringLength(250)]
    public string? NOI_DUNG { get; set; }

    public int? DON_VI_TINH { get; set; }

    public double SO_LUONG { get; set; }

    public double SO_LUONG_HT { get; set; }

    public double SO_LUONG_TRUOC { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? DON_GIA { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? THANH_TIEN { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? PC_MIEN_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? ST_MIEN_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? MIEN_GIAM { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? DA_THU { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? CON_LAI { get; set; }

    [Column(TypeName = "numeric(18, 2)")]
    public decimal? HOAN_TRA { get; set; }

    public int? LOAI_HOAN_TRA { get; set; }

    public int IS_EDITED { get; set; }

    [StringLength(250)]
    public string? GHI_CHU { get; set; }

    [StringLength(150)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(150)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public long? ID_LICH_SU_THANH_TOAN { get; set; }

    [ForeignKey("ID_DM_MIEN_GIAM")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual DM_MIEN_GIAM? ID_DM_MIEN_GIAMNavigation { get; set; }

    [ForeignKey("ID_HOC_SINH")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual HOC_SINH ID_HOC_SINHNavigation { get; set; } = null!;

    [ForeignKey("ID_KHOAN_THU")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual KHOAN_THU? ID_KHOAN_THUNavigation { get; set; }

    [ForeignKey("ID_LOP")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual LOP ID_LOPNavigation { get; set; } = null!;

    [ForeignKey("ID_PHIEU_THU")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual PHIEU_THU ID_PHIEU_THUNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual TRUONG ID_TRUONGNavigation { get; set; } = null!;

    [ForeignKey("MA_CAP_HOC")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual DM_CAP_HOC MA_CAP_HOCNavigation { get; set; } = null!;

    [ForeignKey("MA_NAM_HOC")]
    [InverseProperty("PHIEU_THU_CT")]
    public virtual NAM_HOC MA_NAM_HOCNavigation { get; set; } = null!;
}