// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", "MA_NAM_HOC", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", Name = "IX_NAM_HOC")]
[Index("MA_NAM_HOC", "MA_SO_GD", Name = "IX_SO_NAM_HOC")]
public partial class PHONG_GD
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    [Required]
    [StringLength(20)]
    public string MA { get; set; }

    public int MA_NAM_HOC { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_SO_GD { get; set; }

    [Required]
    [StringLength(250)]
    public string TEN { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_TINH { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HUYEN { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_HUYEN { get; set; }

    [StringLength(250)]
    public string DIA_CHI { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI { get; set; }

    [StringLength(250)]
    public string EMAIL { get; set; }

    [StringLength(250)]
    public string FAX { get; set; }

    [StringLength(250)]
    public string WEBSITE { get; set; }

    [StringLength(250)]
    public string TRUONG_PHONG { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_TRUONG_PHONG { get; set; }

    [StringLength(250)]
    public string EMAIL_TRUONG_PHONG { get; set; }

    [StringLength(250)]
    public string CAN_BO_PHU_TRACH { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_CAN_BO_PHU_TRACH { get; set; }

    [StringLength(250)]
    public string EMAIL_CAN_BO_PHU_TRACH { get; set; }

    public int? THU_TU { get; set; }

    public int? TRANG_THAI { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }
}