// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_DON_VI", "MA_CAP_DON_VI", Name = "IX_CAP_DON_VI_DON_VI")]
[Index("MA", Name = "IX_KEY", IsUnique = true)]
[Index("MA_DON_VI", "MA_CAP_DON_VI", "TEN", Name = "IX_KEY_2", IsUnique = true)]
public partial class PHONG_BAN
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; }

    [StringLength(20)]
    public string MA_PARENT { get; set; }

    [StringLength(20)]
    public string MA_DON_VI { get; set; }

    [StringLength(20)]
    public string MA_CAP_DON_VI { get; set; }

    [StringLength(50)]
    public string MA_NHOM_QUYEN { get; set; }

    [StringLength(250)]
    public string TEN { get; set; }

    [StringLength(500)]
    public string MA_PHAN_CAP { get; set; }

    [StringLength(250)]
    public string DIA_CHI { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI { get; set; }

    [StringLength(250)]
    public string EMAIL { get; set; }

    [StringLength(250)]
    public string FAX { get; set; }

    [StringLength(250)]
    public string WEBSITE { get; set; }

    [StringLength(50)]
    public string TRUONG_DON_VI { get; set; }

    [StringLength(50)]
    public string THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public int? TRANG_THAI { get; set; }

    [StringLength(20)]
    public string MA_BAO_CAO { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_SOURCE { get; set; }

    [ForeignKey("MA_CAP_DON_VI")]
    [InverseProperty("PHONG_BAN")]
    public virtual DM_CAP_DON_VI MA_CAP_DON_VINavigation { get; set; }
}