// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class QUAN_LY_THU_PHI_2025Context : DbContext
{
    public QUAN_LY_THU_PHI_2025Context(DbContextOptions<QUAN_LY_THU_PHI_2025Context> options)
        : base(options)
    {
    }

    public virtual DbSet<API> API { get; set; }

    public virtual DbSet<API_TOKENS> API_TOKENS { get; set; }

    public virtual DbSet<BCS_BIEU_MAU_BC> BCS_BIEU_MAU_BC { get; set; }

    public virtual DbSet<BCS_HOC_SINH_DK_KHOAN_THU> BCS_HOC_SINH_DK_KHOAN_THU { get; set; }

    public virtual DbSet<BCS_HOC_SINH_KHOAN_THU_THANG> BCS_HOC_SINH_KHOAN_THU_THANG { get; set; }

    public virtual DbSet<BCS_HOC_SINH_MIEN_GIAM_KHOAN_THU_THANG> BCS_HOC_SINH_MIEN_GIAM_KHOAN_THU_THANG { get; set; }

    public virtual DbSet<BCS_LOG_GUI_BC> BCS_LOG_GUI_BC { get; set; }

    public virtual DbSet<BCS_MUC_THU_KHOAN_THU> BCS_MUC_THU_KHOAN_THU { get; set; }

    public virtual DbSet<BCS_THU_PHI_KHOAN_THU_THANG> BCS_THU_PHI_KHOAN_THU_THANG { get; set; }

    public virtual DbSet<BCS_TONG_HOP_HTCPHT> BCS_TONG_HOP_HTCPHT { get; set; }

    public virtual DbSet<BCS_TONG_HOP_KENH_THANH_TOAN> BCS_TONG_HOP_KENH_THANH_TOAN { get; set; }

    public virtual DbSet<BCS_TONG_HOP_MIEN_GIAM> BCS_TONG_HOP_MIEN_GIAM { get; set; }

    public virtual DbSet<CAP_MA_BIEN_LAI> CAP_MA_BIEN_LAI { get; set; }

    public virtual DbSet<CAP_MA_HOC_SINH> CAP_MA_HOC_SINH { get; set; }

    public virtual DbSet<CAP_MA_PHIEU_THU> CAP_MA_PHIEU_THU { get; set; }

    public virtual DbSet<CAU_HINH_API_CSDL> CAU_HINH_API_CSDL { get; set; }

    public virtual DbSet<CAU_HINH_API_TRUC_KN> CAU_HINH_API_TRUC_KN { get; set; }

    public virtual DbSet<CAU_HINH_PHIEU_THU> CAU_HINH_PHIEU_THU { get; set; }

    public virtual DbSet<CAU_HINH_TEN_MIEN> CAU_HINH_TEN_MIEN { get; set; }

    public virtual DbSet<CAU_HINH_TRUONG> CAU_HINH_TRUONG { get; set; }

    public virtual DbSet<CH_HS> CH_HS { get; set; }

    public virtual DbSet<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; }

    public virtual DbSet<DIEM_DANH_KHOAN_THU> DIEM_DANH_KHOAN_THU { get; set; }

    public virtual DbSet<DIEM_DANH_KHOAN_THU_KY> DIEM_DANH_KHOAN_THU_KY { get; set; }

    public virtual DbSet<DIEM_DANH_KHOAN_THU_NAM> DIEM_DANH_KHOAN_THU_NAM { get; set; }

    public virtual DbSet<DK_KHOAN_THU_SL_DG> DK_KHOAN_THU_SL_DG { get; set; }

    public virtual DbSet<DK_KHOAN_THU_TN> DK_KHOAN_THU_TN { get; set; }

    public virtual DbSet<DM_CAP_DON_VI> DM_CAP_DON_VI { get; set; }

    public virtual DbSet<DM_CAP_HOC> DM_CAP_HOC { get; set; }

    public virtual DbSet<DM_DAN_TOC> DM_DAN_TOC { get; set; }

    public virtual DbSet<DM_DIEN_CHINH_thuphiCH> DM_DIEN_CHINH_thuphiCH { get; set; }

    public virtual DbSet<DM_DON_VI_CUNG_CAP> DM_DON_VI_CUNG_CAP { get; set; }

    public virtual DbSet<DM_GIOI_TINH> DM_GIOI_TINH { get; set; }

    public virtual DbSet<DM_HINH_THUC_THANH_TOAN> DM_HINH_THUC_THANH_TOAN { get; set; }

    public virtual DbSet<DM_HUYEN> DM_HUYEN { get; set; }

    public virtual DbSet<DM_KHOAN_THU> DM_KHOAN_THU { get; set; }

    public virtual DbSet<DM_KHOAN_THU_SO> DM_KHOAN_THU_SO { get; set; }

    public virtual DbSet<DM_KHOAN_THU_SO_NHOM_DV> DM_KHOAN_THU_SO_NHOM_DV { get; set; }

    public virtual DbSet<DM_KHOI> DM_KHOI { get; set; }

    public virtual DbSet<DM_KHU_VUC> DM_KHU_VUC { get; set; }

    public virtual DbSet<DM_KIEU_LOP> DM_KIEU_LOP { get; set; }

    public virtual DbSet<DM_LOAI_CAN_BO> DM_LOAI_CAN_BO { get; set; }

    public virtual DbSet<DM_LOAI_HINH> DM_LOAI_HINH { get; set; }

    public virtual DbSet<DM_LOAI_KHOAN_THU_SO> DM_LOAI_KHOAN_THU_SO { get; set; }

    public virtual DbSet<DM_LOAI_KHUYET_TAT> DM_LOAI_KHUYET_TAT { get; set; }

    public virtual DbSet<DM_LOAI_TRUONG> DM_LOAI_TRUONG { get; set; }

    public virtual DbSet<DM_MIEN_GIAM> DM_MIEN_GIAM { get; set; }

    public virtual DbSet<DM_MIEN_GIAM_SO> DM_MIEN_GIAM_SO { get; set; }

    public virtual DbSet<DM_MUC_DAT_CHUAN_QG_CLGD> DM_MUC_DAT_CHUAN_QG_CLGD { get; set; }

    public virtual DbSet<DM_NHOM_CAN_BO> DM_NHOM_CAN_BO { get; set; }

    public virtual DbSet<DM_NHOM_KHOAN_THU> DM_NHOM_KHOAN_THU { get; set; }

    public virtual DbSet<DM_NHOM_KHOAN_THU_SO> DM_NHOM_KHOAN_THU_SO { get; set; }

    public virtual DbSet<DM_NHOM_SO> DM_NHOM_SO { get; set; }

    public virtual DbSet<DM_NHOM_SO_QH_AP_DUNG> DM_NHOM_SO_QH_AP_DUNG { get; set; }

    public virtual DbSet<DM_NHOM_TUOI_MN> DM_NHOM_TUOI_MN { get; set; }

    public virtual DbSet<DM_NUOC> DM_NUOC { get; set; }

    public virtual DbSet<DM_PHAN_BAN> DM_PHAN_BAN { get; set; }

    public virtual DbSet<DM_TINH> DM_TINH { get; set; }

    public virtual DbSet<DM_TON_GIAO> DM_TON_GIAO { get; set; }

    public virtual DbSet<DM_TRANG_THAI_HOC_SINH> DM_TRANG_THAI_HOC_SINH { get; set; }

    public virtual DbSet<DM_XA> DM_XA { get; set; }

    public virtual DbSet<DOI_TAC_THANH_TOAN> DOI_TAC_THANH_TOAN { get; set; }

    public virtual DbSet<DOT_THU> DOT_THU { get; set; }

    public virtual DbSet<DOT_THU_DOI_TUONG> DOT_THU_DOI_TUONG { get; set; }

    public virtual DbSet<DOT_THU_KHOAN_THU> DOT_THU_KHOAN_THU { get; set; }

    public virtual DbSet<DOT_THU_TN_CHI_TIET> DOT_THU_TN_CHI_TIET { get; set; }

    public virtual DbSet<DOT_THU_TN_DOI_TUONG> DOT_THU_TN_DOI_TUONG { get; set; }

    public virtual DbSet<DOT_THU_TU_NGUYEN> DOT_THU_TU_NGUYEN { get; set; }

    public virtual DbSet<GUI_THONG_BAO_THU_TIEN> GUI_THONG_BAO_THU_TIEN { get; set; }

    public virtual DbSet<GroupUser> GroupUser { get; set; }

    public virtual DbSet<GroupUserMenu> GroupUserMenu { get; set; }

    public virtual DbSet<GroupUserPGD> GroupUserPGD { get; set; }

    public virtual DbSet<GroupUserPGDMenuPGD> GroupUserPGDMenuPGD { get; set; }

    public virtual DbSet<GroupUserSGD> GroupUserSGD { get; set; }

    public virtual DbSet<GroupUserSGDMenuSGD> GroupUserSGDMenuSGD { get; set; }

    public virtual DbSet<HOA_DON_DIEN_TU> HOA_DON_DIEN_TU { get; set; }

    public virtual DbSet<HOC_SINH> HOC_SINH { get; set; }

    public virtual DbSet<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; }

    public virtual DbSet<KHOAN_THU> KHOAN_THU { get; set; }

    public virtual DbSet<KHOAN_THU_DOI_TUONG> KHOAN_THU_DOI_TUONG { get; set; }

    public virtual DbSet<KHOAN_THU_MIEN_GIAM> KHOAN_THU_MIEN_GIAM { get; set; }

    public virtual DbSet<KHOA_DIEM_DANH> KHOA_DIEM_DANH { get; set; }

    public virtual DbSet<KHOA_DIEM_DANH_KY> KHOA_DIEM_DANH_KY { get; set; }

    public virtual DbSet<KHOA_DIEM_DANH_NAM> KHOA_DIEM_DANH_NAM { get; set; }

    public virtual DbSet<LICH_SU_HOAN_TIEN_CONG_THANH_TOAN> LICH_SU_HOAN_TIEN_CONG_THANH_TOAN { get; set; }

    public virtual DbSet<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; }

    public virtual DbSet<LICH_SU_THU_TIEN> LICH_SU_THU_TIEN { get; set; }

    public virtual DbSet<LICH_SU_THU_TIEN_CT> LICH_SU_THU_TIEN_CT { get; set; }

    public virtual DbSet<LOP> LOP { get; set; }

    public virtual DbSet<MAP_MIEN_GIAM_HS> MAP_MIEN_GIAM_HS { get; set; }

    public virtual DbSet<MAP_MIEN_GIAM_HS_SO> MAP_MIEN_GIAM_HS_SO { get; set; }

    public virtual DbSet<Menu> Menu { get; set; }

    public virtual DbSet<MenuPGD> MenuPGD { get; set; }

    public virtual DbSet<MenuSGD> MenuSGD { get; set; }

    public virtual DbSet<NAM_HOC> NAM_HOC { get; set; }

    public virtual DbSet<NGAY_HOC_THANG> NGAY_HOC_THANG { get; set; }

    public virtual DbSet<NGAY_NGHI_TRONG_NAM> NGAY_NGHI_TRONG_NAM { get; set; }

    public virtual DbSet<NGAY_TRONG_NAM> NGAY_TRONG_NAM { get; set; }

    public virtual DbSet<NGUOI_DUNG> NGUOI_DUNG { get; set; }

    public virtual DbSet<NHAN_SU> NHAN_SU { get; set; }

    public virtual DbSet<NHAN_SU_LOP_CHU_NHIEM> NHAN_SU_LOP_CHU_NHIEM { get; set; }

    public virtual DbSet<NHOM_DIEM_DANH> NHOM_DIEM_DANH { get; set; }

    public virtual DbSet<PHAN_QUYEN_API> PHAN_QUYEN_API { get; set; }

    public virtual DbSet<PHIEU_THU> PHIEU_THU { get; set; }

    public virtual DbSet<PHIEU_THU_CT> PHIEU_THU_CT { get; set; }

    public virtual DbSet<PHONG_BAN> PHONG_BAN { get; set; }

    public virtual DbSet<PHONG_GD> PHONG_GD { get; set; }

    public virtual DbSet<QUYEN_NGUOI_DUNG> QUYEN_NGUOI_DUNG { get; set; }

    public virtual DbSet<SO_GD> SO_GD { get; set; }

    public virtual DbSet<TAI_KHOAN_GUI_TIN> TAI_KHOAN_GUI_TIN { get; set; }

    public virtual DbSet<TAI_KHOAN_GUI_TIN_TRUC_KN> TAI_KHOAN_GUI_TIN_TRUC_KN { get; set; }

    public virtual DbSet<THONG_BAO_DIEU_HANH> THONG_BAO_DIEU_HANH { get; set; }

    public virtual DbSet<THONG_BAO_DOI_TUONG> THONG_BAO_DOI_TUONG { get; set; }

    public virtual DbSet<TRUONG> TRUONG { get; set; }

    public virtual DbSet<TRUONG_DANG_KY_SU_DUNG> TRUONG_DANG_KY_SU_DUNG { get; set; }

    public virtual DbSet<TRUONG_DOI_TAC_THANH_TOAN> TRUONG_DOI_TAC_THANH_TOAN { get; set; }

    public virtual DbSet<XEM_THONG_BAO> XEM_THONG_BAO { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<API_TOKENS>(entity =>
        {
            entity.Property(e => e.EXPIRES_ON).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<BCS_BIEU_MAU_BC>(entity =>
        {
            entity.Property(e => e.NGAY_TAO).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<BCS_HOC_SINH_DK_KHOAN_THU>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_HOC___3214EC27F09C5462");
        });

        modelBuilder.Entity<BCS_HOC_SINH_KHOAN_THU_THANG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_HOC___3214EC275C3B4057");
        });

        modelBuilder.Entity<BCS_HOC_SINH_MIEN_GIAM_KHOAN_THU_THANG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_HOC___3214EC27D78CD569");
        });

        modelBuilder.Entity<BCS_LOG_GUI_BC>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_LOG___3214EC274C605534");
        });

        modelBuilder.Entity<BCS_MUC_THU_KHOAN_THU>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_MUC___3214EC27E76A1DBE");
        });

        modelBuilder.Entity<BCS_THU_PHI_KHOAN_THU_THANG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_THU___3214EC276A25EF37");
        });

        modelBuilder.Entity<BCS_TONG_HOP_KENH_THANH_TOAN>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__BCS_TONG__3214EC27B86B2415");
        });

        modelBuilder.Entity<CAP_MA_HOC_SINH>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CAP_MA_H__3214EC27AE7C9040");
        });

        modelBuilder.Entity<CAU_HINH_API_CSDL>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CAU_HINH__3214EC2724A65661");
        });

        modelBuilder.Entity<CAU_HINH_API_TRUC_KN>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CAU_HINH__3214EC27DD23A5CC");
        });

        modelBuilder.Entity<CAU_HINH_PHIEU_THU>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__CAU_HINH__3214EC27C9B9664C");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.CAU_HINH_PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAU_HINH_PHIEU_THU_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.CAU_HINH_PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAU_HINH_PHIEU_THU_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.CAU_HINH_PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CAU_HINH_PHIEU_THU_NAM_HOC");
        });

        modelBuilder.Entity<CAU_HINH_TRUONG>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
            entity.Property(e => e.IS_KHONG_HIEN_HOC_SINH_KHONG_HOC).HasComment("Không hiện học sinh nghỉ học, chuyển trường, kỷ luật, miễn môn...(mặc định là hiện):\r\n0: Có hiện\r\n1: Không hiện");
            entity.Property(e => e.THANG_CUOI_KY_I).HasDefaultValue(12);
            entity.Property(e => e.THANG_CUOI_KY_II).HasDefaultValue(6);
            entity.Property(e => e.THANG_DAU_KY_I).HasDefaultValue(7);
            entity.Property(e => e.THANG_DAU_KY_II).HasDefaultValue(1);
        });

        modelBuilder.Entity<DIEM_DANH_HS_NHOM>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_HOC_SINH");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_LOP");

            entity.HasOne(d => d.ID_NHOM_DIEM_DANHNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_NHOM_DIEM_DANH");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DIEM_DANH_HS_NHOM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_HS_NHOM_NAM_HOC");
        });

        modelBuilder.Entity<DIEM_DANH_KHOAN_THU>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_HOC");
        });

        modelBuilder.Entity<DIEM_DANH_KHOAN_THU_KY>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_KY_NAM_HOC");
        });

        modelBuilder.Entity<DIEM_DANH_KHOAN_THU_NAM>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DIEM_DANH_KHOAN_THU_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DIEM_DANH_KHOAN_THU_NAM_NAM_HOC");
        });

        modelBuilder.Entity<DK_KHOAN_THU_SL_DG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DK_KHOAN__3214EC271F3A3BD7");

            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_SL_DG_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG).HasConstraintName("FK_DK_KHOAN_THU_SL_DG_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_SL_DG_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_SL_DG_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_SL_DG_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DK_KHOAN_THU_SL_DG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_SL_DG_NAM_HOC");
        });

        modelBuilder.Entity<DK_KHOAN_THU_TN>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DK_KHOAN_THU_TN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DK_KHOAN_THU_TN_NAM_HOC");
        });

        modelBuilder.Entity<DM_CAP_HOC>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_CAP_HOC_1");
        });

        modelBuilder.Entity<DM_DAN_TOC>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_DAN_TOC_1");
        });

        modelBuilder.Entity<DM_DON_VI_CUNG_CAP>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_DON_V__3214EC274DF57A0F");
        });

        modelBuilder.Entity<DM_GIOI_TINH>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_GIOI_TINH_1");
        });

        modelBuilder.Entity<DM_HUYEN>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.MA_TINHNavigation).WithMany(p => p.DM_HUYEN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DM_HUYEN_DM_TINH");
        });

        modelBuilder.Entity<DM_KHOAN_THU_SO>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_KHOAN__3214EC27A7BE0811");
        });

        modelBuilder.Entity<DM_KHOAN_THU_SO_NHOM_DV>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_KHOAN__3214EC279B6CC9F5");
        });

        modelBuilder.Entity<DM_KHOI>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_KHOI");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DM_KHOI).HasConstraintName("FK_DM_KHOI_DM_CAP_HOC");
        });

        modelBuilder.Entity<DM_KHU_VUC>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_KHU_VUC_1");
        });

        modelBuilder.Entity<DM_LOAI_HINH>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<DM_LOAI_KHOAN_THU_SO>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_LOAI___3214EC27BDDAAB29");
        });

        modelBuilder.Entity<DM_LOAI_TRUONG>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_LOAI_TRUONG_1");
        });

        modelBuilder.Entity<DM_MUC_DAT_CHUAN_QG_CLGD>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_DM_MUC_DAT_CHUAN_QG_CLGD_1");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<DM_NHOM_KHOAN_THU_SO>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_NHOM___3214EC2724566267");
        });

        modelBuilder.Entity<DM_NHOM_SO>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_NHOM__3214EC27EF893AA8");
        });

        modelBuilder.Entity<DM_NHOM_SO_QH_AP_DUNG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__DM_NHOM___3214EC279770D155");
        });

        modelBuilder.Entity<DM_TINH>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_TINH_1");
        });

        modelBuilder.Entity<DM_TON_GIAO>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_DM_TON_GIAO_1");
        });

        modelBuilder.Entity<DM_XA>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_DM_XA_1");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.ID_HUYENNavigation).WithMany(p => p.DM_XA).HasConstraintName("FK_DM_XA_DM_HUYEN");

            entity.HasOne(d => d.MA_TINHNavigation).WithMany(p => p.DM_XA)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DM_XA_DM_TINH");
        });

        modelBuilder.Entity<DOT_THU>(entity =>
        {
            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DOT_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DOT_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DOT_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_NAM_HOC");
        });

        modelBuilder.Entity<DOT_THU_DOI_TUONG>(entity =>
        {
            entity.HasOne(d => d.ID_DOT_THUNavigation).WithMany(p => p.DOT_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_DOI_TUONG_DOT_THU");

            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.DOT_THU_DOI_TUONG).HasConstraintName("FK_DOT_THU_DOI_TUONG_HOC_SINH");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.DOT_THU_DOI_TUONG).HasConstraintName("FK_DOT_THU_DOI_TUONG_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DOT_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_DOI_TUONG_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DOT_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_DOI_TUONG_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DOT_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_DOI_TUONG_NAM_HOC");
        });

        modelBuilder.Entity<DOT_THU_KHOAN_THU>(entity =>
        {
            entity.HasOne(d => d.ID_DOT_THUNavigation).WithMany(p => p.DOT_THU_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_KHOAN_THU_DOT_THU");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.DOT_THU_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_KHOAN_THU_KHOAN_THU");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DOT_THU_KHOAN_THU).HasConstraintName("FK_DOT_THU_KHOAN_THU_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DOT_THU_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_KHOAN_THU_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DOT_THU_KHOAN_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_KHOAN_THU_NAM_HOC");
        });

        modelBuilder.Entity<DOT_THU_TN_CHI_TIET>(entity =>
        {
            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.DOT_THU_TN_CHI_TIET)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_TN_CHI_TIET_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.DOT_THU_TN_CHI_TIET)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_TN_CHI_TIET_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.DOT_THU_TN_CHI_TIET)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DOT_THU_TN_CHI_TIET_NAM_HOC");
        });

        modelBuilder.Entity<GUI_THONG_BAO_THU_TIEN>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_GUI_THON_BAO_THU_PHI");
        });

        modelBuilder.Entity<GroupUserMenu>(entity =>
        {
            entity.Property(e => e.GroupUserMenuID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.GroupUser).WithMany(p => p.GroupUserMenu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserMenu_GroupUser");

            entity.HasOne(d => d.Menu).WithMany(p => p.GroupUserMenu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserMenu_Menu");
        });

        modelBuilder.Entity<GroupUserPGDMenuPGD>(entity =>
        {
            entity.Property(e => e.GroupUserPGDMenuPGDID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.GroupUserPGD).WithMany(p => p.GroupUserPGDMenuPGD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserPGDMenuPGD_GroupUserPGD");

            entity.HasOne(d => d.MenuPGD).WithMany(p => p.GroupUserPGDMenuPGD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserPGDMenuPGD_MenuPGD");
        });

        modelBuilder.Entity<GroupUserSGDMenuSGD>(entity =>
        {
            entity.Property(e => e.GroupUserSGDMenuSGDID).ValueGeneratedOnAdd();

            entity.HasOne(d => d.GroupUserSGD).WithMany(p => p.GroupUserSGDMenuSGD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserSGDMenuSGD_GroupUserSGD");

            entity.HasOne(d => d.MenuSGD).WithMany(p => p.GroupUserSGDMenuSGD)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupUserSGDMenuSGD_MenuSGD");
        });

        modelBuilder.Entity<HOC_SINH>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<HOC_SINH_MIEN_GIAM>(entity =>
        {
            entity.Property(e => e.GHI_CHU).HasDefaultValueSql("((0))");

            entity.HasOne(d => d.ID_DM_MIEN_GIAMNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HOC_SINH_MIEN_GIAM_DM_MIEN_GIAM");

            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HOC_SINH_MIEN_GIAM_HOC_SINH");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM).HasConstraintName("FK_HOC_SINH_MIEN_GIAM_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HOC_SINH_MIEN_GIAM_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HOC_SINH_MIEN_GIAM_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.HOC_SINH_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HOC_SINH_MIEN_GIAM_NAM_HOC");
        });

        modelBuilder.Entity<KHOAN_THU_DOI_TUONG>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG).HasConstraintName("FK_KHOAN_THU_DOI_TUONG_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_DOI_TUONG_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG).HasConstraintName("FK_KHOAN_THU_DOI_TUONG_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_DOI_TUONG_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_DOI_TUONG_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.KHOAN_THU_DOI_TUONG)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_DOI_TUONG_NAM_HOC");
        });

        modelBuilder.Entity<KHOAN_THU_MIEN_GIAM>(entity =>
        {
            entity.HasOne(d => d.ID_DM_MIEN_GIAMNavigation).WithMany(p => p.KHOAN_THU_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_MIEN_GIAM_DM_MIEN_GIAM");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.KHOAN_THU_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_MIEN_GIAM_KHOAN_THU");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.KHOAN_THU_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_MIEN_GIAM_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.KHOAN_THU_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_MIEN_GIAM_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.KHOAN_THU_MIEN_GIAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOAN_THU_MIEN_GIAM_NAM_HOC");
        });

        modelBuilder.Entity<KHOA_DIEM_DANH>(entity =>
        {
            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.KHOA_DIEM_DANH)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.KHOA_DIEM_DANH)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_NAM_HOC");
        });

        modelBuilder.Entity<KHOA_DIEM_DANH_KY>(entity =>
        {
            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.KHOA_DIEM_DANH_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_KY_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.KHOA_DIEM_DANH_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_KY_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_KY_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH_KY)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_KY_NAM_HOC");
        });

        modelBuilder.Entity<KHOA_DIEM_DANH_NAM>(entity =>
        {
            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.KHOA_DIEM_DANH_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_NAM_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.KHOA_DIEM_DANH_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_NAM_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_NAM_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.KHOA_DIEM_DANH_NAM)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_KHOA_DIEM_DANH_NAM_NAM_HOC");
        });

        modelBuilder.Entity<LICH_SU_HOAN_TIEN_CONG_THANH_TOAN>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__LICH_SU___3214EC27D3270EBB");
        });

        modelBuilder.Entity<LICH_SU_THANH_TOAN>(entity =>
        {
            entity.HasOne(d => d.ID_DOT_THUNavigation).WithMany(p => p.LICH_SU_THANH_TOAN).HasConstraintName("FK_LICH_SU_THANH_TOAN_DOT_THU");

            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.LICH_SU_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THANH_TOAN_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.LICH_SU_THANH_TOAN).HasConstraintName("FK_LICH_SU_THANH_TOAN_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.LICH_SU_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THANH_TOAN_LOP");

            entity.HasOne(d => d.ID_PHIEU_THUNavigation).WithMany(p => p.LICH_SU_THANH_TOAN).HasConstraintName("FK_LICH_SU_THANH_TOAN_PHIEU_THU");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.LICH_SU_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THANH_TOAN_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.LICH_SU_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THANH_TOAN_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.LICH_SU_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THANH_TOAN_NAM_HOC");
        });

        modelBuilder.Entity<LICH_SU_THU_TIEN_CT>(entity =>
        {
            entity.HasOne(d => d.ID_LSTTNavigation).WithMany(p => p.LICH_SU_THU_TIEN_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LICH_SU_THU_TIEN_CT_LICH_SU_THU_TIEN");
        });

        modelBuilder.Entity<LOP>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_LOP_1");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<MAP_MIEN_GIAM_HS>(entity =>
        {
            entity.HasOne(d => d.ID_CH_HSNavigation).WithMany(p => p.MAP_MIEN_GIAM_HS)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MAP_MIEN_GIAM_HS_CH_HS");

            entity.HasOne(d => d.ID_DM_MIEN_GIAMNavigation).WithMany(p => p.MAP_MIEN_GIAM_HS)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MAP_MIEN_GIAM_HS_DM_MIEN_GIAM");
        });

        modelBuilder.Entity<MAP_MIEN_GIAM_HS_SO>(entity =>
        {
            entity.HasOne(d => d.ID_CH_HSNavigation).WithMany(p => p.MAP_MIEN_GIAM_HS_SO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MAP_MIEN_GIAM_HS_SO_CH_HS");

            entity.HasOne(d => d.ID_DM_MIEN_GIAM_SONavigation).WithMany(p => p.MAP_MIEN_GIAM_HS_SO)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MAP_MIEN_GIAM_HS_SO_DM_MIEN_GIAM_SO");
        });

        modelBuilder.Entity<NAM_HOC>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_NAM_HOC_1");

            entity.Property(e => e.MA).ValueGeneratedNever();
        });

        modelBuilder.Entity<NGUOI_DUNG>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<NHAN_SU>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<NHAN_SU_LOP_CHU_NHIEM>(entity =>
        {
            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<PHIEU_THU>(entity =>
        {
            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_HOC_SINH");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_LOP");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.PHIEU_THU)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_NAM_HOC");
        });

        modelBuilder.Entity<PHIEU_THU_CT>(entity =>
        {
            entity.HasOne(d => d.ID_DM_MIEN_GIAMNavigation).WithMany(p => p.PHIEU_THU_CT).HasConstraintName("FK_PHIEU_THU_CT_DM_MIEN_GIAM");

            entity.HasOne(d => d.ID_HOC_SINHNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_HOC_SINH");

            entity.HasOne(d => d.ID_KHOAN_THUNavigation).WithMany(p => p.PHIEU_THU_CT).HasConstraintName("FK_PHIEU_THU_CT_KHOAN_THU");

            entity.HasOne(d => d.ID_LOPNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_LOP");

            entity.HasOne(d => d.ID_PHIEU_THUNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_PHIEU_THU");

            entity.HasOne(d => d.ID_TRUONGNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_TRUONG");

            entity.HasOne(d => d.MA_CAP_HOCNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_DM_CAP_HOC");

            entity.HasOne(d => d.MA_NAM_HOCNavigation).WithMany(p => p.PHIEU_THU_CT)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PHIEU_THU_CT_NAM_HOC");
        });

        modelBuilder.Entity<PHONG_BAN>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_PHONG_BAN_1");

            entity.HasOne(d => d.MA_CAP_DON_VINavigation).WithMany(p => p.PHONG_BAN).HasConstraintName("FK_PHONG_BAN_DM_CAP_DON_VI");
        });

        modelBuilder.Entity<PHONG_GD>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_PHONG_GD_1");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<SO_GD>(entity =>
        {
            entity.HasKey(e => e.MA).HasName("PK_SO_GD_1");
        });

        modelBuilder.Entity<TAI_KHOAN_GUI_TIN>(entity =>
        {
            entity.Property(e => e.NGAY_TAO).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TAI_KHOAN_GUI_TIN_TRUC_KN>(entity =>
        {
            entity.Property(e => e.NGAY_TAO).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<TRUONG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_TRUONG_1");

            entity.Property(e => e.ID).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TRUONG_DANG_KY_SU_DUNG>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_TRUONG_DANG_KY_THU");
        });

        modelBuilder.Entity<TRUONG_DOI_TAC_THANH_TOAN>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_TRUONG_DANG_KY_KENH_THANH_TOAN");

            entity.HasOne(d => d.ID_DOI_TAC_THANH_TOANNavigation).WithMany(p => p.TRUONG_DOI_TAC_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TRUONG_DOI_TAC_THANH_TOAN_DOI_TAC_THANH_TOAN");

            entity.HasOne(d => d.ID_TRUONG_DANG_KY_SU_DUNGNavigation).WithMany(p => p.TRUONG_DOI_TAC_THANH_TOAN)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TRUONG_DOI_TAC_THANH_TOAN_TRUONG_DANG_KY_SU_DUNG");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}