// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class QUYEN_NGUOI_DUNG
{
    [Key]
    public long ID { get; set; }

    [StringLength(50)]
    public string MA_SO_GD { get; set; }

    [StringLength(50)]
    public string MA_TRUONG { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_NGUOI_DUNG { get; set; }

    [StringLength(50)]
    public string MA_NGUOI_DUNG { get; set; }

    public long ID_NHOM_QUYEN { get; set; }

    [StringLength(50)]
    public string NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(50)]
    public string NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }
}