// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class RefreshToken
{
    [Key]
    public long ID { get; set; }

    public string TOKEN { get; set; } = null!;

    [Column(TypeName = "numeric(18, 0)")]
    public decimal NGUOI_DUNG_ID { get; set; }

    [StringLength(50)]
    public string? APP_VERSION { get; set; }

    public long MA_NAM_HOC { get; set; }

    public long HOC_KY { get; set; }

    [StringLength(50)]
    public string? MA_CAP_HOC { get; set; }

    [StringLength(50)]
    public string? MA_SO_GD { get; set; }

    [StringLength(50)]
    public string? MA_TRUONG { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EXPERIED_DATE { get; set; }

    public Guid? USER_VERSION { get; set; }
}