// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA", Name = "IX_KEY", IsUnique = true)]
public partial class SO_GD
{
    [Key]
    [StringLength(20)]
    public string MA { get; set; } = null!;

    [StringLength(250)]
    public string TEN { get; set; } = null!;

    [StringLength(20)]
    public string MA_TINH { get; set; } = null!;

    [StringLength(250)]
    public string? DIA_CHI { get; set; }

    [StringLength(20)]
    public string? DIEN_THOAI { get; set; }

    [StringLength(250)]
    public string? EMAIL { get; set; }

    [StringLength(250)]
    public string? FAX { get; set; }

    [StringLength(250)]
    public string? WEBSITE { get; set; }

    [StringLength(250)]
    public string? GIAM_DOC { get; set; }

    [StringLength(20)]
    public string? DIEN_THOAI_GIAM_DOC { get; set; }

    [StringLength(250)]
    public string? EMAIL_GIAM_DOC { get; set; }

    [StringLength(250)]
    public string? CHANH_VAN_PHONG { get; set; }

    [StringLength(20)]
    public string? DIEN_THOAI_CHANH_VAN_PHONG { get; set; }

    [StringLength(250)]
    public string? EMAIL_CHANH_VAN_PHONG { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public int? TRANG_THAI { get; set; }

    [StringLength(200)]
    public string? TEN_DIA_PHUONG { get; set; }

    [StringLength(20)]
    public string MA_SOURCE { get; set; } = null!;

    public int? IS_BC_EX { get; set; }
}