// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable dithuphible
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

[Index("MA_NAM_HOC", "MA", Name = "IX_KEY", IsUnique = true)]
[Index("MA_NAM_HOC", "MA_SO_GD", Name = "IX_NAM_SO")]
public partial class TRUONG
{
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID { get; set; }

    public int MA_NAM_HOC { get; set; }

    [StringLength(20)]
    public string MA_SO_GD { get; set; }

    [Required]
    [StringLength(20)]
    public string MA { get; set; }

    [Required]
    [StringLength(200)]
    public string TEN { get; set; }

    [Required]
    [StringLength(20)]
    public string MA_NHOM_CAP_HOC { get; set; }

    [StringLength(20)]
    public string DS_CAP_HOC { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_PHONG_GD { get; set; }

    [StringLength(20)]
    public string MA_PHONG_GD { get; set; }

    [StringLength(20)]
    public string MA_TINH { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_HUYEN { get; set; }

    [StringLength(20)]
    public string MA_HUYEN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? ID_XA { get; set; }

    [StringLength(20)]
    public string MA_XA { get; set; }

    [StringLength(1000)]
    public string DIA_CHI { get; set; }

    [StringLength(20)]
    public string MA_LOAI_HINH_TRUONG { get; set; }

    [StringLength(20)]
    public string MA_LOAI_TRUONG { get; set; }

    [StringLength(20)]
    public string MA_KHU_VUC { get; set; }

    [StringLength(20)]
    public string MA_DAT_CHUAN_DANH_GIA_CLGD { get; set; }

    [StringLength(20)]
    public string MA_TRUC_THUOC { get; set; }

    [StringLength(20)]
    public string MA_DU_AN { get; set; }

    public int? SO_DIEM_TRUONG { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI { get; set; }

    [StringLength(250)]
    public string EMAIL { get; set; }

    [StringLength(20)]
    public string FAX { get; set; }

    [StringLength(250)]
    public string WEBSITE { get; set; }

    [StringLength(50)]
    public string VI_TRI_BAN_DO { get; set; }

    [StringLength(250)]
    public string HIEU_TRUONG { get; set; }

    [StringLength(20)]
    public string DIEN_THOAI_HIEU_TRUONG { get; set; }

    [StringLength(250)]
    public string EMAIL_HIEU_TRUONG { get; set; }

    public int? IS_CO_CHI_BO_DANG { get; set; }

    public int? IS_DAT_CHUAN_QG { get; set; }

    public int? IS_TRUONG_QUOC_TE { get; set; }

    public int? IS_CAP_MN { get; set; }

    public int? IS_CAP_TH { get; set; }

    public int? IS_CAP_THCS { get; set; }

    public int? IS_CAP_THPT { get; set; }

    public int? IS_CAP_GDTX { get; set; }

    public int? THU_TU { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    public int? TRANG_THAI { get; set; }

    public int? IS_CO_LOP_NHO { get; set; }

    public int? IS_NHO_TREN { get; set; }

    public int? IS_NHO_DUOI { get; set; }

    [StringLength(50)]
    public string KINH_TUYEN { get; set; }

    [StringLength(50)]
    public string VI_TUYEN { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_SOURCE { get; set; }

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<CAU_HINH_PHIEU_THU> CAU_HINH_PHIEU_THU { get; set; } = new List<CAU_HINH_PHIEU_THU>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DIEM_DANH_HS_NHOM> DIEM_DANH_HS_NHOM { get; set; } = new List<DIEM_DANH_HS_NHOM>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU> DIEM_DANH_KHOAN_THU { get; set; } = new List<DIEM_DANH_KHOAN_THU>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_KY> DIEM_DANH_KHOAN_THU_KY { get; set; } = new List<DIEM_DANH_KHOAN_THU_KY>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DIEM_DANH_KHOAN_THU_NAM> DIEM_DANH_KHOAN_THU_NAM { get; set; } = new List<DIEM_DANH_KHOAN_THU_NAM>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DK_KHOAN_THU_SL_DG> DK_KHOAN_THU_SL_DG { get; set; } = new List<DK_KHOAN_THU_SL_DG>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DK_KHOAN_THU_TN> DK_KHOAN_THU_TN { get; set; } = new List<DK_KHOAN_THU_TN>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DOT_THU> DOT_THU { get; set; } = new List<DOT_THU>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DOT_THU_DOI_TUONG> DOT_THU_DOI_TUONG { get; set; } = new List<DOT_THU_DOI_TUONG>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DOT_THU_KHOAN_THU> DOT_THU_KHOAN_THU { get; set; } = new List<DOT_THU_KHOAN_THU>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<DOT_THU_TN_CHI_TIET> DOT_THU_TN_CHI_TIET { get; set; } = new List<DOT_THU_TN_CHI_TIET>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<HOC_SINH_MIEN_GIAM> HOC_SINH_MIEN_GIAM { get; set; } = new List<HOC_SINH_MIEN_GIAM>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<KHOAN_THU_DOI_TUONG> KHOAN_THU_DOI_TUONG { get; set; } = new List<KHOAN_THU_DOI_TUONG>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<KHOAN_THU_MIEN_GIAM> KHOAN_THU_MIEN_GIAM { get; set; } = new List<KHOAN_THU_MIEN_GIAM>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH> KHOA_DIEM_DANH { get; set; } = new List<KHOA_DIEM_DANH>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_KY> KHOA_DIEM_DANH_KY { get; set; } = new List<KHOA_DIEM_DANH_KY>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<KHOA_DIEM_DANH_NAM> KHOA_DIEM_DANH_NAM { get; set; } = new List<KHOA_DIEM_DANH_NAM>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<LICH_SU_THANH_TOAN> LICH_SU_THANH_TOAN { get; set; } = new List<LICH_SU_THANH_TOAN>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<PHIEU_THU> PHIEU_THU { get; set; } = new List<PHIEU_THU>();

    [InverseProperty("ID_TRUONGNavigation")]
    public virtual ICollection<PHIEU_THU_CT> PHIEU_THU_CT { get; set; } = new List<PHIEU_THU_CT>();
}