// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

[Index("ID_DOI_TAC_THANH_TOAN", "ID_TRUONG_DANG_KY_SU_DUNG", Name = "IX_TRUONG_DANG_KY_KENH_THANH_TOAN_UNIQUE", IsUnique = true)]
public partial class TRUONG_DOI_TAC_THANH_TOAN
{
    [Key]
    public long ID { get; set; }

    public long ID_TRUONG_DANG_KY_SU_DUNG { get; set; }

    public long ID_DOI_TAC_THANH_TOAN { get; set; }

    public int IS_DANG_KY { get; set; }

    [StringLength(50)]
    public string? NGUOI_TAO { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_TAO { get; set; }

    [StringLength(50)]
    public string? NGUOI_SUA { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? NGAY_SUA { get; set; }

    [ForeignKey("ID_DOI_TAC_THANH_TOAN")]
    [InverseProperty("TRUONG_DOI_TAC_THANH_TOAN")]
    public virtual DOI_TAC_THANH_TOAN ID_DOI_TAC_THANH_TOANNavigation { get; set; } = null!;

    [ForeignKey("ID_TRUONG_DANG_KY_SU_DUNG")]
    [InverseProperty("TRUONG_DOI_TAC_THANH_TOAN")]
    public virtual TRUONG_DANG_KY_SU_DUNG ID_TRUONG_DANG_KY_SU_DUNGNavigation { get; set; } = null!;
}