// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.SQL.QLTP.Models;

public partial class XEM_THONG_BAO
{
    [Key]
    public long ID { get; set; }

    public long ID_THONG_BAO_DIEU_HANH { get; set; }

    [StringLength(250)]
    public string? MA_SO_GD { get; set; }

    [StringLength(250)]
    public string? MA_PHONG_GD { get; set; }

    [StringLength(250)]
    public string? MA_TRUONG { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal ID_NGUOI_DUNG { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime THOI_GIAN_XEM { get; set; }
}